// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"
	"time"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	SessionCookieScopes = "sessionCookie.Scopes"
)

// Defines values for AccountRole.
const (
	AccountRoleADMIN      AccountRole = "ADMIN"
	AccountRoleSUPERADMIN AccountRole = "SUPER_ADMIN"
	AccountRoleUSER       AccountRole = "USER"
)

// Defines values for AccountStatus.
const (
	AccountStatusACTIVE   AccountStatus = "ACTIVE"
	AccountStatusDISABLED AccountStatus = "DISABLED"
)

// Defines values for GoalStatus.
const (
	GoalStatusCANCELLED  GoalStatus = "CANCELLED"
	GoalStatusCOMPLETED  GoalStatus = "COMPLETED"
	GoalStatusINPROGRESS GoalStatus = "IN_PROGRESS"
	GoalStatusNOTSTARTED GoalStatus = "NOT_STARTED"
	GoalStatusPAUSED     GoalStatus = "PAUSED"
)

// Defines values for GoalType.
const (
	GoalTypeDAY      GoalType = "DAY"
	GoalTypeLONGTERM GoalType = "LONG_TERM"
	GoalTypeMONTH    GoalType = "MONTH"
	GoalTypeSTAGE    GoalType = "STAGE"
	GoalTypeWEEK     GoalType = "WEEK"
	GoalTypeYEAR     GoalType = "YEAR"
)

// Defines values for GoalMetricMetricCode.
const (
	GoalMetricMetricCodeAudioMinutes          GoalMetricMetricCode = "audio_minutes"
	GoalMetricMetricCodeBufferCount           GoalMetricMetricCode = "buffer_count"
	GoalMetricMetricCodeConversationOpenCount GoalMetricMetricCode = "conversation_open_count"
	GoalMetricMetricCodeCustomerFollowupCount GoalMetricMetricCode = "customer_followup_count"
	GoalMetricMetricCodeDeepConversationCount GoalMetricMetricCode = "deep_conversation_count"
	GoalMetricMetricCodeMeetingCount          GoalMetricMetricCode = "meeting_count"
	GoalMetricMetricCodeOpportunityCount      GoalMetricMetricCode = "opportunity_count"
	GoalMetricMetricCodeReadingMinutes        GoalMetricMetricCode = "reading_minutes"
	GoalMetricMetricCodeScreeningCount        GoalMetricMetricCode = "screening_count"
	GoalMetricMetricCodeStoryShareCount       GoalMetricMetricCode = "story_share_count"
	GoalMetricMetricCodeTurnoverNetAmount     GoalMetricMetricCode = "turnover_net_amount"
	GoalMetricMetricCodeTurnoverPv            GoalMetricMetricCode = "turnover_pv"
)

// Defines values for GoalRequestMetricsMetricCode.
const (
	GoalRequestMetricsMetricCodeAudioMinutes          GoalRequestMetricsMetricCode = "audio_minutes"
	GoalRequestMetricsMetricCodeBufferCount           GoalRequestMetricsMetricCode = "buffer_count"
	GoalRequestMetricsMetricCodeConversationOpenCount GoalRequestMetricsMetricCode = "conversation_open_count"
	GoalRequestMetricsMetricCodeCustomerFollowupCount GoalRequestMetricsMetricCode = "customer_followup_count"
	GoalRequestMetricsMetricCodeDeepConversationCount GoalRequestMetricsMetricCode = "deep_conversation_count"
	GoalRequestMetricsMetricCodeMeetingCount          GoalRequestMetricsMetricCode = "meeting_count"
	GoalRequestMetricsMetricCodeOpportunityCount      GoalRequestMetricsMetricCode = "opportunity_count"
	GoalRequestMetricsMetricCodeReadingMinutes        GoalRequestMetricsMetricCode = "reading_minutes"
	GoalRequestMetricsMetricCodeScreeningCount        GoalRequestMetricsMetricCode = "screening_count"
	GoalRequestMetricsMetricCodeStoryShareCount       GoalRequestMetricsMetricCode = "story_share_count"
	GoalRequestMetricsMetricCodeTurnoverNetAmount     GoalRequestMetricsMetricCode = "turnover_net_amount"
	GoalRequestMetricsMetricCodeTurnoverPv            GoalRequestMetricsMetricCode = "turnover_pv"
)

// Defines values for GoalRequestStatus.
const (
	GoalRequestStatusCANCELLED  GoalRequestStatus = "CANCELLED"
	GoalRequestStatusCOMPLETED  GoalRequestStatus = "COMPLETED"
	GoalRequestStatusINPROGRESS GoalRequestStatus = "IN_PROGRESS"
	GoalRequestStatusNOTSTARTED GoalRequestStatus = "NOT_STARTED"
	GoalRequestStatusPAUSED     GoalRequestStatus = "PAUSED"
)

// Defines values for GoalRequestType.
const (
	GoalRequestTypeDAY      GoalRequestType = "DAY"
	GoalRequestTypeLONGTERM GoalRequestType = "LONG_TERM"
	GoalRequestTypeMONTH    GoalRequestType = "MONTH"
	GoalRequestTypeSTAGE    GoalRequestType = "STAGE"
	GoalRequestTypeWEEK     GoalRequestType = "WEEK"
	GoalRequestTypeYEAR     GoalRequestType = "YEAR"
)

// Defines values for HealthDataChecks.
const (
	Ready       HealthDataChecks = "ready"
	Unavailable HealthDataChecks = "unavailable"
)

// Defines values for HealthDataStatus.
const (
	Ok HealthDataStatus = "ok"
)

// Defines values for InvitationStatus.
const (
	InvitationStatusACTIVE   InvitationStatus = "ACTIVE"
	InvitationStatusDISABLED InvitationStatus = "DISABLED"
)

// Defines values for SessionAccountRole.
const (
	SessionAccountRoleADMIN      SessionAccountRole = "ADMIN"
	SessionAccountRoleSUPERADMIN SessionAccountRole = "SUPER_ADMIN"
	SessionAccountRoleUSER       SessionAccountRole = "USER"
)

// Defines values for SessionAccountStatus.
const (
	SessionAccountStatusACTIVE   SessionAccountStatus = "ACTIVE"
	SessionAccountStatusDISABLED SessionAccountStatus = "DISABLED"
)

// Defines values for StatusRequestStatus.
const (
	StatusRequestStatusACTIVE   StatusRequestStatus = "ACTIVE"
	StatusRequestStatusDISABLED StatusRequestStatus = "DISABLED"
)

// Defines values for UpdateInvitationRequestStatus.
const (
	ACTIVE   UpdateInvitationRequestStatus = "ACTIVE"
	DISABLED UpdateInvitationRequestStatus = "DISABLED"
)

// Account defines model for Account.
type Account struct {
	CreatedAt   time.Time          `json:"created_at"`
	Id          openapi_types.UUID `json:"id"`
	LastLoginAt *time.Time         `json:"last_login_at"`
	Role        AccountRole        `json:"role"`
	Status      AccountStatus      `json:"status"`
	Timezone    string             `json:"timezone"`
	Username    string             `json:"username"`
}

// AccountRole defines model for Account.Role.
type AccountRole string

// AccountStatus defines model for Account.Status.
type AccountStatus string

// AccountResponse defines model for AccountResponse.
type AccountResponse struct {
	Data      Account `json:"data"`
	RequestId string  `json:"request_id"`
}

// AccountsData defines model for AccountsData.
type AccountsData struct {
	Account   Account          `json:"account"`
	Accounts  []SessionAccount `json:"accounts"`
	CsrfToken string           `json:"csrf_token"`
}

// AccountsListData defines model for AccountsListData.
type AccountsListData struct {
	Items []Account `json:"items"`
}

// AccountsListResponse defines model for AccountsListResponse.
type AccountsListResponse struct {
	Data      AccountsListData `json:"data"`
	Meta      PaginationMeta   `json:"meta"`
	RequestId string           `json:"request_id"`
}

// AccountsResponse defines model for AccountsResponse.
type AccountsResponse struct {
	Data      AccountsData `json:"data"`
	RequestId string       `json:"request_id"`
}

// AuthData defines model for AuthData.
type AuthData struct {
	Account   Account          `json:"account"`
	Accounts  []SessionAccount `json:"accounts"`
	CsrfToken string           `json:"csrf_token"`
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	Data      AuthData `json:"data"`
	RequestId string   `json:"request_id"`
}

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	CurrentPassword string `json:"current_password"`
	NewPassword     string `json:"new_password"`
}

// CreateAdminRequest defines model for CreateAdminRequest.
type CreateAdminRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// CreateInvitationRequest defines model for CreateInvitationRequest.
type CreateInvitationRequest struct {
	Code      *string    `json:"code,omitempty"`
	ExpiresAt *time.Time `json:"expires_at"`
	MaxUses   *int       `json:"max_uses"`
}

// CsrfData defines model for CsrfData.
type CsrfData struct {
	CsrfToken string `json:"csrf_token"`
}

// CsrfResponse defines model for CsrfResponse.
type CsrfResponse struct {
	Data      CsrfData `json:"data"`
	RequestId string   `json:"request_id"`
}

// DashboardData defines model for DashboardData.
type DashboardData struct {
	ActiveGoals []Goal             `json:"active_goals"`
	Date        openapi_types.Date `json:"date"`
	DreamsCount int                `json:"dreams_count"`
	Month       DashboardPeriod    `json:"month"`
	Today       DashboardPeriod    `json:"today"`
	Week        DashboardPeriod    `json:"week"`
}

// DashboardPeriod defines model for DashboardPeriod.
type DashboardPeriod struct {
	From     openapi_types.Date `json:"from"`
	To       openapi_types.Date `json:"to"`
	Turnover TurnoverTotals     `json:"turnover"`
	Worklogs WorklogTotals      `json:"worklogs"`
}

// DashboardResponse defines model for DashboardResponse.
type DashboardResponse struct {
	Data      DashboardData `json:"data"`
	RequestId string        `json:"request_id"`
}

// Dream defines model for Dream.
type Dream struct {
	CreatedAt   time.Time            `json:"created_at"`
	Description *string              `json:"description"`
	GoalIds     []openapi_types.UUID `json:"goal_ids"`
	Id          openapi_types.UUID   `json:"id"`
	SortOrder   int                  `json:"sort_order"`
	Title       string               `json:"title"`
	UpdatedAt   time.Time            `json:"updated_at"`
}

// DreamListResponse defines model for DreamListResponse.
type DreamListResponse struct {
	Data struct {
		Items []Dream `json:"items"`
	} `json:"data"`
	RequestId string `json:"request_id"`
}

// DreamRequest defines model for DreamRequest.
type DreamRequest struct {
	Description *string               `json:"description"`
	GoalIds     *[]openapi_types.UUID `json:"goal_ids,omitempty"`
	SortOrder   *int                  `json:"sort_order,omitempty"`
	Title       string                `json:"title"`
}

// DreamResponse defines model for DreamResponse.
type DreamResponse struct {
	Data      Dream  `json:"data"`
	RequestId string `json:"request_id"`
}

// ErrorBody defines model for ErrorBody.
type ErrorBody struct {
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`
	Message string                  `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error     ErrorBody `json:"error"`
	RequestId string    `json:"request_id"`
}

// Goal defines model for Goal.
type Goal struct {
	CreatedAt   time.Time           `json:"created_at"`
	Description *string             `json:"description"`
	DueDate     *openapi_types.Date `json:"due_date"`
	Id          openapi_types.UUID  `json:"id"`
	Metrics     []GoalMetric        `json:"metrics"`
	ParentId    *openapi_types.UUID `json:"parent_id"`
	Progress    float32             `json:"progress"`
	SortOrder   int                 `json:"sort_order"`
	StartDate   *openapi_types.Date `json:"start_date"`
	Status      GoalStatus          `json:"status"`
	Title       string              `json:"title"`
	Type        GoalType            `json:"type"`
	UpdatedAt   time.Time           `json:"updated_at"`
}

// GoalStatus defines model for Goal.Status.
type GoalStatus string

// GoalType defines model for Goal.Type.
type GoalType string

// GoalListResponse defines model for GoalListResponse.
type GoalListResponse struct {
	Data struct {
		Items []Goal `json:"items"`
	} `json:"data"`
	RequestId string `json:"request_id"`
}

// GoalMetric defines model for GoalMetric.
type GoalMetric struct {
	ActualValue float32              `json:"actual_value"`
	MetricCode  GoalMetricMetricCode `json:"metric_code"`
	Progress    float32              `json:"progress"`
	TargetValue float32              `json:"target_value"`
	Unit        string               `json:"unit"`
}

// GoalMetricMetricCode defines model for GoalMetric.MetricCode.
type GoalMetricMetricCode string

// GoalRequest defines model for GoalRequest.
type GoalRequest struct {
	Description *string             `json:"description"`
	DueDate     *openapi_types.Date `json:"due_date"`
	Metrics     *[]struct {
		MetricCode  GoalRequestMetricsMetricCode `json:"metric_code"`
		TargetValue float32                      `json:"target_value"`
		Unit        string                       `json:"unit"`
	} `json:"metrics,omitempty"`
	ParentId  *openapi_types.UUID `json:"parent_id"`
	SortOrder *int                `json:"sort_order,omitempty"`
	StartDate *openapi_types.Date `json:"start_date"`
	Status    *GoalRequestStatus  `json:"status,omitempty"`
	Title     string              `json:"title"`
	Type      GoalRequestType     `json:"type"`
}

// GoalRequestMetricsMetricCode defines model for GoalRequest.Metrics.MetricCode.
type GoalRequestMetricsMetricCode string

// GoalRequestStatus defines model for GoalRequest.Status.
type GoalRequestStatus string

// GoalRequestType defines model for GoalRequest.Type.
type GoalRequestType string

// GoalResponse defines model for GoalResponse.
type GoalResponse struct {
	Data      Goal   `json:"data"`
	RequestId string `json:"request_id"`
}

// HealthData defines model for HealthData.
type HealthData struct {
	Checks map[string]HealthDataChecks `json:"checks"`
	Status HealthDataStatus            `json:"status"`
}

// HealthDataChecks defines model for HealthData.Checks.
type HealthDataChecks string

// HealthDataStatus defines model for HealthData.Status.
type HealthDataStatus string

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Data      HealthData `json:"data"`
	RequestId string     `json:"request_id"`
}

// Invitation defines model for Invitation.
type Invitation struct {
	Code      string             `json:"code"`
	CreatedAt time.Time          `json:"created_at"`
	ExpiresAt *time.Time         `json:"expires_at"`
	Id        openapi_types.UUID `json:"id"`
	MaxUses   *int               `json:"max_uses"`
	Status    InvitationStatus   `json:"status"`
	UsedCount int                `json:"used_count"`
}

// InvitationStatus defines model for Invitation.Status.
type InvitationStatus string

// InvitationListResponse defines model for InvitationListResponse.
type InvitationListResponse struct {
	Data struct {
		Items []Invitation `json:"items"`
	} `json:"data"`
	RequestId string `json:"request_id"`
}

// InvitationResponse defines model for InvitationResponse.
type InvitationResponse struct {
	Data      Invitation `json:"data"`
	RequestId string     `json:"request_id"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// PaginationMeta defines model for PaginationMeta.
type PaginationMeta struct {
	Page     int `json:"page"`
	PageSize int `json:"page_size"`
	Total    int `json:"total"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	InvitationCode string `json:"invitation_code"`
	Password       string `json:"password"`
	Username       string `json:"username"`
}

// ResetPasswordData defines model for ResetPasswordData.
type ResetPasswordData struct {
	TemporaryPassword string `json:"temporary_password"`
}

// ResetPasswordRequest defines model for ResetPasswordRequest.
type ResetPasswordRequest struct {
	TemporaryPassword *string `json:"temporary_password,omitempty"`
}

// ResetPasswordResponse defines model for ResetPasswordResponse.
type ResetPasswordResponse struct {
	Data      ResetPasswordData `json:"data"`
	RequestId string            `json:"request_id"`
}

// SessionAccount defines model for SessionAccount.
type SessionAccount struct {
	Active      bool                 `json:"active"`
	CreatedAt   time.Time            `json:"created_at"`
	Id          openapi_types.UUID   `json:"id"`
	LastLoginAt *time.Time           `json:"last_login_at"`
	Role        SessionAccountRole   `json:"role"`
	Status      SessionAccountStatus `json:"status"`
	Timezone    string               `json:"timezone"`
	Username    string               `json:"username"`
}

// SessionAccountRole defines model for SessionAccount.Role.
type SessionAccountRole string

// SessionAccountStatus defines model for SessionAccount.Status.
type SessionAccountStatus string

// StatusRequest defines model for StatusRequest.
type StatusRequest struct {
	Status StatusRequestStatus `json:"status"`
}

// StatusRequestStatus defines model for StatusRequest.Status.
type StatusRequestStatus string

// TimezoneRequest defines model for TimezoneRequest.
type TimezoneRequest struct {
	Timezone string `json:"timezone"`
}

// Turnover defines model for Turnover.
type Turnover struct {
	CreatedAt    time.Time          `json:"created_at"`
	Id           openapi_types.UUID `json:"id"`
	NetAmount    float32            `json:"net_amount"`
	Note         *string            `json:"note"`
	Pv           float32            `json:"pv"`
	TurnoverDate openapi_types.Date `json:"turnover_date"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

// TurnoverListResponse defines model for TurnoverListResponse.
type TurnoverListResponse struct {
	Data struct {
		Items []Turnover `json:"items"`
	} `json:"data"`
	RequestId string `json:"request_id"`
}

// TurnoverRequest defines model for TurnoverRequest.
type TurnoverRequest struct {
	NetAmount    *float32           `json:"net_amount"`
	Note         *string            `json:"note"`
	Pv           *float32           `json:"pv"`
	TurnoverDate openapi_types.Date `json:"turnover_date"`
}

// TurnoverResponse defines model for TurnoverResponse.
type TurnoverResponse struct {
	Data      Turnover `json:"data"`
	RequestId string   `json:"request_id"`
}

// TurnoverTotals defines model for TurnoverTotals.
type TurnoverTotals struct {
	NetAmount float32 `json:"net_amount"`
	Pv        float32 `json:"pv"`
}

// UpdateInvitationRequest defines model for UpdateInvitationRequest.
type UpdateInvitationRequest struct {
	// ClearExpiresAt Clear expires_at and make the code non-expiring.
	ClearExpiresAt *bool `json:"clear_expires_at,omitempty"`

	// ClearMaxUses Clear max_uses and make the code unlimited.
	ClearMaxUses *bool                          `json:"clear_max_uses,omitempty"`
	ExpiresAt    *time.Time                     `json:"expires_at"`
	MaxUses      *int                           `json:"max_uses"`
	Status       *UpdateInvitationRequestStatus `json:"status,omitempty"`
}

// UpdateInvitationRequestStatus defines model for UpdateInvitationRequest.Status.
type UpdateInvitationRequestStatus string

// Worklog defines model for Worklog.
type Worklog struct {
	AudioMinutes          int                `json:"audio_minutes"`
	BufferCount           int                `json:"buffer_count"`
	CreatedAt             time.Time          `json:"created_at"`
	CustomerFollowupCount int                `json:"customer_followup_count"`
	DeepConversationCount int                `json:"deep_conversation_count"`
	Id                    openapi_types.UUID `json:"id"`
	MeetingCount          int                `json:"meeting_count"`
	Note                  *string            `json:"note"`
	OpenConversationCount int                `json:"open_conversation_count"`
	OpportunityCount      int                `json:"opportunity_count"`
	ReadingMinutes        int                `json:"reading_minutes"`
	ScreeningCount        int                `json:"screening_count"`
	StoryShareCount       int                `json:"story_share_count"`
	TurnoverNetAmount     *float32           `json:"turnover_net_amount"`
	TurnoverPv            *float32           `json:"turnover_pv"`
	UpdatedAt             time.Time          `json:"updated_at"`
	WorkDate              openapi_types.Date `json:"work_date"`
}

// WorklogListResponse defines model for WorklogListResponse.
type WorklogListResponse struct {
	Data struct {
		Items []Worklog `json:"items"`
	} `json:"data"`
	RequestId string `json:"request_id"`
}

// WorklogRequest defines model for WorklogRequest.
type WorklogRequest struct {
	AudioMinutes          int                `json:"audio_minutes"`
	BufferCount           int                `json:"buffer_count"`
	CustomerFollowupCount int                `json:"customer_followup_count"`
	DeepConversationCount int                `json:"deep_conversation_count"`
	MeetingCount          int                `json:"meeting_count"`
	Note                  *string            `json:"note"`
	OpenConversationCount int                `json:"open_conversation_count"`
	OpportunityCount      int                `json:"opportunity_count"`
	ReadingMinutes        int                `json:"reading_minutes"`
	ScreeningCount        int                `json:"screening_count"`
	StoryShareCount       int                `json:"story_share_count"`
	TurnoverNetAmount     *float32           `json:"turnover_net_amount"`
	TurnoverPv            *float32           `json:"turnover_pv"`
	WorkDate              openapi_types.Date `json:"work_date"`
}

// WorklogResponse defines model for WorklogResponse.
type WorklogResponse struct {
	Data      Worklog `json:"data"`
	RequestId string  `json:"request_id"`
}

// WorklogTotals defines model for WorklogTotals.
type WorklogTotals struct {
	AudioMinutes          int `json:"audio_minutes"`
	BufferCount           int `json:"buffer_count"`
	CustomerFollowupCount int `json:"customer_followup_count"`
	DeepConversationCount int `json:"deep_conversation_count"`
	MeetingCount          int `json:"meeting_count"`
	OpenConversationCount int `json:"open_conversation_count"`
	OpportunityCount      int `json:"opportunity_count"`
	ReadingMinutes        int `json:"reading_minutes"`
	ScreeningCount        int `json:"screening_count"`
	StoryShareCount       int `json:"story_share_count"`
}

// AccountId defines model for AccountId.
type AccountId = openapi_types.UUID

// BusinessDate defines model for BusinessDate.
type BusinessDate = openapi_types.Date

// DateFrom defines model for DateFrom.
type DateFrom = openapi_types.Date

// DateTo defines model for DateTo.
type DateTo = openapi_types.Date

// DreamId defines model for DreamId.
type DreamId = openapi_types.UUID

// GoalId defines model for GoalId.
type GoalId = openapi_types.UUID

// InvitationId defines model for InvitationId.
type InvitationId = openapi_types.UUID

// Page defines model for Page.
type Page = int

// PageSize defines model for PageSize.
type PageSize = int

// TurnoverDate defines model for TurnoverDate.
type TurnoverDate = openapi_types.Date

// WorkDate defines model for WorkDate.
type WorkDate = openapi_types.Date

// GetAdminUsersParams defines parameters for GetAdminUsers.
type GetAdminUsersParams struct {
	Page     *Page     `form:"page,omitempty" json:"page,omitempty"`
	PageSize *PageSize `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// GetDashboardParams defines parameters for GetDashboard.
type GetDashboardParams struct {
	Date BusinessDate `form:"date" json:"date"`
}

// ListTurnoversParams defines parameters for ListTurnovers.
type ListTurnoversParams struct {
	From *DateFrom `form:"from,omitempty" json:"from,omitempty"`
	To   *DateTo   `form:"to,omitempty" json:"to,omitempty"`
}

// ListWorklogsParams defines parameters for ListWorklogs.
type ListWorklogsParams struct {
	From *DateFrom `form:"from,omitempty" json:"from,omitempty"`
	To   *DateTo   `form:"to,omitempty" json:"to,omitempty"`
}

// PostAdminAdminJSONRequestBody defines body for PostAdminAdmin for application/json ContentType.
type PostAdminAdminJSONRequestBody = CreateAdminRequest

// PatchAdminAdminJSONRequestBody defines body for PatchAdminAdmin for application/json ContentType.
type PatchAdminAdminJSONRequestBody = StatusRequest

// PostAdminAdminResetPasswordJSONRequestBody defines body for PostAdminAdminResetPassword for application/json ContentType.
type PostAdminAdminResetPasswordJSONRequestBody = ResetPasswordRequest

// PostAdminInvitationCodeJSONRequestBody defines body for PostAdminInvitationCode for application/json ContentType.
type PostAdminInvitationCodeJSONRequestBody = CreateInvitationRequest

// PatchAdminInvitationCodeJSONRequestBody defines body for PatchAdminInvitationCode for application/json ContentType.
type PatchAdminInvitationCodeJSONRequestBody = UpdateInvitationRequest

// PostAdminUserResetPasswordJSONRequestBody defines body for PostAdminUserResetPassword for application/json ContentType.
type PostAdminUserResetPasswordJSONRequestBody = ResetPasswordRequest

// PatchAdminUserStatusJSONRequestBody defines body for PatchAdminUserStatus for application/json ContentType.
type PatchAdminUserStatusJSONRequestBody = StatusRequest

// PostAuthAccountsAddJSONRequestBody defines body for PostAuthAccountsAdd for application/json ContentType.
type PostAuthAccountsAddJSONRequestBody = LoginRequest

// PostAuthChangePasswordJSONRequestBody defines body for PostAuthChangePassword for application/json ContentType.
type PostAuthChangePasswordJSONRequestBody = ChangePasswordRequest

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = LoginRequest

// PatchAuthTimezoneJSONRequestBody defines body for PatchAuthTimezone for application/json ContentType.
type PatchAuthTimezoneJSONRequestBody = TimezoneRequest

// PostAuthRegisterJSONRequestBody defines body for PostAuthRegister for application/json ContentType.
type PostAuthRegisterJSONRequestBody = RegisterRequest

// CreateDreamJSONRequestBody defines body for CreateDream for application/json ContentType.
type CreateDreamJSONRequestBody = DreamRequest

// UpdateDreamJSONRequestBody defines body for UpdateDream for application/json ContentType.
type UpdateDreamJSONRequestBody = DreamRequest

// CreateGoalJSONRequestBody defines body for CreateGoal for application/json ContentType.
type CreateGoalJSONRequestBody = GoalRequest

// UpdateGoalJSONRequestBody defines body for UpdateGoal for application/json ContentType.
type UpdateGoalJSONRequestBody = GoalRequest

// CreateTurnoverJSONRequestBody defines body for CreateTurnover for application/json ContentType.
type CreateTurnoverJSONRequestBody = TurnoverRequest

// UpdateTurnoverJSONRequestBody defines body for UpdateTurnover for application/json ContentType.
type UpdateTurnoverJSONRequestBody = TurnoverRequest

// CreateWorklogJSONRequestBody defines body for CreateWorklog for application/json ContentType.
type CreateWorklogJSONRequestBody = WorklogRequest

// UpdateWorklogJSONRequestBody defines body for UpdateWorklog for application/json ContentType.
type UpdateWorklogJSONRequestBody = WorklogRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List ordinary administrators
	// (GET /api/admin/admins)
	GetAdminAdmins(ctx echo.Context) error
	// Create an ordinary administrator
	// (POST /api/admin/admins)
	PostAdminAdmin(ctx echo.Context) error
	// Delete an ordinary administrator
	// (DELETE /api/admin/admins/{account_id})
	DeleteAdminAdmin(ctx echo.Context, accountId AccountId) error
	// Enable or disable an ordinary administrator
	// (PATCH /api/admin/admins/{account_id})
	PatchAdminAdmin(ctx echo.Context, accountId AccountId) error
	// Reset an ordinary administrator password
	// (POST /api/admin/admins/{account_id}/reset-password)
	PostAdminAdminResetPassword(ctx echo.Context, accountId AccountId) error
	// List invitation codes
	// (GET /api/admin/invitation-codes)
	GetAdminInvitationCodes(ctx echo.Context) error
	// Create an invitation code
	// (POST /api/admin/invitation-codes)
	PostAdminInvitationCode(ctx echo.Context) error
	// Disable an invitation code
	// (DELETE /api/admin/invitation-codes/{invitation_id})
	DeleteAdminInvitationCode(ctx echo.Context, invitationId InvitationId) error
	// Update invitation status or limits
	// (PATCH /api/admin/invitation-codes/{invitation_id})
	PatchAdminInvitationCode(ctx echo.Context, invitationId InvitationId) error
	// List normal users without business data
	// (GET /api/admin/users)
	GetAdminUsers(ctx echo.Context, params GetAdminUsersParams) error
	// Delete a normal user and its online access
	// (DELETE /api/admin/users/{account_id})
	DeleteAdminUser(ctx echo.Context, accountId AccountId) error
	// Reset a normal user password
	// (POST /api/admin/users/{account_id}/reset-password)
	PostAdminUserResetPassword(ctx echo.Context, accountId AccountId) error
	// Enable or disable a normal user
	// (PATCH /api/admin/users/{account_id}/status)
	PatchAdminUserStatus(ctx echo.Context, accountId AccountId) error
	// List normal accounts linked to this browser session
	// (GET /api/auth/accounts)
	GetAuthAccounts(ctx echo.Context) error
	// Authenticate and add another normal account to this browser session
	// (POST /api/auth/accounts/add)
	PostAuthAccountsAdd(ctx echo.Context) error
	// Remove a linked normal account from this browser session
	// (DELETE /api/auth/accounts/{account_id})
	DeleteAuthAccount(ctx echo.Context, accountId AccountId) error
	// Switch the active normal account without re-entering its password
	// (POST /api/auth/accounts/{account_id}/switch)
	PostAuthAccountsSwitch(ctx echo.Context, accountId AccountId) error
	// Change the active account password
	// (POST /api/auth/change-password)
	PostAuthChangePassword(ctx echo.Context) error
	// Return the CSRF token for the current browser session
	// (GET /api/auth/csrf)
	GetAuthCsrf(ctx echo.Context) error
	// Sign in an account
	// (POST /api/auth/login)
	PostAuthLogin(ctx echo.Context) error
	// End the current browser session
	// (POST /api/auth/logout)
	PostAuthLogout(ctx echo.Context) error
	// Return the active account
	// (GET /api/auth/me)
	GetAuthMe(ctx echo.Context) error
	// Change the active account timezone
	// (PATCH /api/auth/me/timezone)
	PatchAuthTimezone(ctx echo.Context) error
	// Register a normal user with an invitation code
	// (POST /api/auth/register)
	PostAuthRegister(ctx echo.Context) error
	// Return the user dashboard aggregates for a business date
	// (GET /api/dashboard)
	GetDashboard(ctx echo.Context, params GetDashboardParams) error
	// List dreams for the current user
	// (GET /api/dreams)
	ListDreams(ctx echo.Context) error
	// Create a dream
	// (POST /api/dreams)
	CreateDream(ctx echo.Context) error
	// Delete a dream
	// (DELETE /api/dreams/{dream_id})
	DeleteDream(ctx echo.Context, dreamId DreamId) error
	// Get a dream
	// (GET /api/dreams/{dream_id})
	GetDream(ctx echo.Context, dreamId DreamId) error
	// Replace a dream
	// (PUT /api/dreams/{dream_id})
	UpdateDream(ctx echo.Context, dreamId DreamId) error
	// List goals with calculated progress
	// (GET /api/goals)
	ListGoals(ctx echo.Context) error
	// Create a goal
	// (POST /api/goals)
	CreateGoal(ctx echo.Context) error
	// Delete a goal and its descendants
	// (DELETE /api/goals/{goal_id})
	DeleteGoal(ctx echo.Context, goalId GoalId) error
	// Get a goal with calculated progress
	// (GET /api/goals/{goal_id})
	GetGoal(ctx echo.Context, goalId GoalId) error
	// Replace a goal
	// (PUT /api/goals/{goal_id})
	UpdateGoal(ctx echo.Context, goalId GoalId) error
	// Check whether the API process is live
	// (GET /api/health/live)
	GetHealthLive(ctx echo.Context) error
	// Check whether required runtime dependencies are ready
	// (GET /api/health/ready)
	GetHealthReady(ctx echo.Context) error
	// List daily turnovers in a business-date range
	// (GET /api/turnover)
	ListTurnovers(ctx echo.Context, params ListTurnoversParams) error
	// Create or replace a daily turnover
	// (POST /api/turnover)
	CreateTurnover(ctx echo.Context) error
	// Delete turnover for a business date
	// (DELETE /api/turnover/{turnover_date})
	DeleteTurnover(ctx echo.Context, turnoverDate TurnoverDate) error
	// Get turnover for a business date
	// (GET /api/turnover/{turnover_date})
	GetTurnover(ctx echo.Context, turnoverDate TurnoverDate) error
	// Replace turnover for a business date
	// (PUT /api/turnover/{turnover_date})
	UpdateTurnover(ctx echo.Context, turnoverDate TurnoverDate) error
	// List daily worklogs in a business-date range
	// (GET /api/worklogs)
	ListWorklogs(ctx echo.Context, params ListWorklogsParams) error
	// Create or replace a daily worklog
	// (POST /api/worklogs)
	CreateWorklog(ctx echo.Context) error
	// Delete a daily worklog
	// (DELETE /api/worklogs/{work_date})
	DeleteWorklog(ctx echo.Context, workDate WorkDate) error
	// Get a daily worklog
	// (GET /api/worklogs/{work_date})
	GetWorklog(ctx echo.Context, workDate WorkDate) error
	// Replace a daily worklog
	// (PUT /api/worklogs/{work_date})
	UpdateWorklog(ctx echo.Context, workDate WorkDate) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetAdminAdmins converts echo context to params.
func (w *ServerInterfaceWrapper) GetAdminAdmins(ctx echo.Context) error {
	var err error

	ctx.Set(SessionCookieScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAdminAdmins(ctx)
	return err
}

// PostAdminAdmin converts echo context to params.
func (w *ServerInterfaceWrapper) PostAdminAdmin(ctx echo.Context) error {
	var err error

	ctx.Set(SessionCookieScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostAdminAdmin(ctx)
	return err
}

// DeleteAdminAdmin converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteAdminAdmin(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "account_id" -------------
	var accountId AccountId

	err = runtime.BindStyledParameterWithOptions("simple", "account_id", ctx.Param("account_id"), &accountId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter account_id: %s", err))
	}

	ctx.Set(SessionCookieScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteAdminAdmin(ctx, accountId)
	return err
}

// PatchAdminAdmin converts echo context to params.
func (w *ServerInterfaceWrapper) PatchAdminAdmin(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "account_id" -------------
	var accountId AccountId

	err = runtime.BindStyledParameterWithOptions("simple", "account_id", ctx.Param("account_id"), &accountId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter account_id: %s", err))
	}

	ctx.Set(SessionCookieScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PatchAdminAdmin(ctx, accountId)
	return err
}

// PostAdminAdminResetPassword converts echo context to params.
func (w *ServerInterfaceWrapper) PostAdminAdminResetPassword(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "account_id" -------------
	var accountId AccountId

	err = runtime.BindStyledParameterWithOptions("simple", "account_id", ctx.Param("account_id"), &accountId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter account_id: %s", err))
	}

	ctx.Set(SessionCookieScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostAdminAdminResetPassword(ctx, accountId)
	return err
}

// GetAdminInvitationCodes converts echo context to params.
func (w *ServerInterfaceWrapper) GetAdminInvitationCodes(ctx echo.Context) error {
	var err error

	ctx.Set(SessionCookieScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAdminInvitationCodes(ctx)
	return err
}

// PostAdminInvitationCode converts echo context to params.
func (w *ServerInterfaceWrapper) PostAdminInvitationCode(ctx echo.Context) error {
	var err error

	ctx.Set(SessionCookieScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostAdminInvitationCode(ctx)
	return err
}

// DeleteAdminInvitationCode converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteAdminInvitationCode(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "invitation_id" -------------
	var invitationId InvitationId

	err = runtime.BindStyledParameterWithOptions("simple", "invitation_id", ctx.Param("invitation_id"), &invitationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter invitation_id: %s", err))
	}

	ctx.Set(SessionCookieScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteAdminInvitationCode(ctx, invitationId)
	return err
}

// PatchAdminInvitationCode converts echo context to params.
func (w *ServerInterfaceWrapper) PatchAdminInvitationCode(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "invitation_id" -------------
	var invitationId InvitationId

	err = runtime.BindStyledParameterWithOptions("simple", "invitation_id", ctx.Param("invitation_id"), &invitationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter invitation_id: %s", err))
	}

	ctx.Set(SessionCookieScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PatchAdminInvitationCode(ctx, invitationId)
	return err
}

// GetAdminUsers converts echo context to params.
func (w *ServerInterfaceWrapper) GetAdminUsers(ctx echo.Context) error {
	var err error

	ctx.Set(SessionCookieScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAdminUsersParams
	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_size", ctx.QueryParams(), &params.PageSize)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page_size: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAdminUsers(ctx, params)
	return err
}

// DeleteAdminUser converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteAdminUser(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "account_id" -------------
	var accountId AccountId

	err = runtime.BindStyledParameterWithOptions("simple", "account_id", ctx.Param("account_id"), &accountId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter account_id: %s", err))
	}

	ctx.Set(SessionCookieScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteAdminUser(ctx, accountId)
	return err
}

// PostAdminUserResetPassword converts echo context to params.
func (w *ServerInterfaceWrapper) PostAdminUserResetPassword(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "account_id" -------------
	var accountId AccountId

	err = runtime.BindStyledParameterWithOptions("simple", "account_id", ctx.Param("account_id"), &accountId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter account_id: %s", err))
	}

	ctx.Set(SessionCookieScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostAdminUserResetPassword(ctx, accountId)
	return err
}

// PatchAdminUserStatus converts echo context to params.
func (w *ServerInterfaceWrapper) PatchAdminUserStatus(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "account_id" -------------
	var accountId AccountId

	err = runtime.BindStyledParameterWithOptions("simple", "account_id", ctx.Param("account_id"), &accountId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter account_id: %s", err))
	}

	ctx.Set(SessionCookieScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PatchAdminUserStatus(ctx, accountId)
	return err
}

// GetAuthAccounts converts echo context to params.
func (w *ServerInterfaceWrapper) GetAuthAccounts(ctx echo.Context) error {
	var err error

	ctx.Set(SessionCookieScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAuthAccounts(ctx)
	return err
}

// PostAuthAccountsAdd converts echo context to params.
func (w *ServerInterfaceWrapper) PostAuthAccountsAdd(ctx echo.Context) error {
	var err error

	ctx.Set(SessionCookieScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostAuthAccountsAdd(ctx)
	return err
}

// DeleteAuthAccount converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteAuthAccount(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "account_id" -------------
	var accountId AccountId

	err = runtime.BindStyledParameterWithOptions("simple", "account_id", ctx.Param("account_id"), &accountId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter account_id: %s", err))
	}

	ctx.Set(SessionCookieScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteAuthAccount(ctx, accountId)
	return err
}

// PostAuthAccountsSwitch converts echo context to params.
func (w *ServerInterfaceWrapper) PostAuthAccountsSwitch(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "account_id" -------------
	var accountId AccountId

	err = runtime.BindStyledParameterWithOptions("simple", "account_id", ctx.Param("account_id"), &accountId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter account_id: %s", err))
	}

	ctx.Set(SessionCookieScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostAuthAccountsSwitch(ctx, accountId)
	return err
}

// PostAuthChangePassword converts echo context to params.
func (w *ServerInterfaceWrapper) PostAuthChangePassword(ctx echo.Context) error {
	var err error

	ctx.Set(SessionCookieScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostAuthChangePassword(ctx)
	return err
}

// GetAuthCsrf converts echo context to params.
func (w *ServerInterfaceWrapper) GetAuthCsrf(ctx echo.Context) error {
	var err error

	ctx.Set(SessionCookieScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAuthCsrf(ctx)
	return err
}

// PostAuthLogin converts echo context to params.
func (w *ServerInterfaceWrapper) PostAuthLogin(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostAuthLogin(ctx)
	return err
}

// PostAuthLogout converts echo context to params.
func (w *ServerInterfaceWrapper) PostAuthLogout(ctx echo.Context) error {
	var err error

	ctx.Set(SessionCookieScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostAuthLogout(ctx)
	return err
}

// GetAuthMe converts echo context to params.
func (w *ServerInterfaceWrapper) GetAuthMe(ctx echo.Context) error {
	var err error

	ctx.Set(SessionCookieScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAuthMe(ctx)
	return err
}

// PatchAuthTimezone converts echo context to params.
func (w *ServerInterfaceWrapper) PatchAuthTimezone(ctx echo.Context) error {
	var err error

	ctx.Set(SessionCookieScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PatchAuthTimezone(ctx)
	return err
}

// PostAuthRegister converts echo context to params.
func (w *ServerInterfaceWrapper) PostAuthRegister(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostAuthRegister(ctx)
	return err
}

// GetDashboard converts echo context to params.
func (w *ServerInterfaceWrapper) GetDashboard(ctx echo.Context) error {
	var err error

	ctx.Set(SessionCookieScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDashboardParams
	// ------------- Required query parameter "date" -------------

	err = runtime.BindQueryParameter("form", true, true, "date", ctx.QueryParams(), &params.Date)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter date: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetDashboard(ctx, params)
	return err
}

// ListDreams converts echo context to params.
func (w *ServerInterfaceWrapper) ListDreams(ctx echo.Context) error {
	var err error

	ctx.Set(SessionCookieScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListDreams(ctx)
	return err
}

// CreateDream converts echo context to params.
func (w *ServerInterfaceWrapper) CreateDream(ctx echo.Context) error {
	var err error

	ctx.Set(SessionCookieScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateDream(ctx)
	return err
}

// DeleteDream converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteDream(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "dream_id" -------------
	var dreamId DreamId

	err = runtime.BindStyledParameterWithOptions("simple", "dream_id", ctx.Param("dream_id"), &dreamId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter dream_id: %s", err))
	}

	ctx.Set(SessionCookieScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteDream(ctx, dreamId)
	return err
}

// GetDream converts echo context to params.
func (w *ServerInterfaceWrapper) GetDream(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "dream_id" -------------
	var dreamId DreamId

	err = runtime.BindStyledParameterWithOptions("simple", "dream_id", ctx.Param("dream_id"), &dreamId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter dream_id: %s", err))
	}

	ctx.Set(SessionCookieScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetDream(ctx, dreamId)
	return err
}

// UpdateDream converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateDream(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "dream_id" -------------
	var dreamId DreamId

	err = runtime.BindStyledParameterWithOptions("simple", "dream_id", ctx.Param("dream_id"), &dreamId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter dream_id: %s", err))
	}

	ctx.Set(SessionCookieScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateDream(ctx, dreamId)
	return err
}

// ListGoals converts echo context to params.
func (w *ServerInterfaceWrapper) ListGoals(ctx echo.Context) error {
	var err error

	ctx.Set(SessionCookieScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListGoals(ctx)
	return err
}

// CreateGoal converts echo context to params.
func (w *ServerInterfaceWrapper) CreateGoal(ctx echo.Context) error {
	var err error

	ctx.Set(SessionCookieScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateGoal(ctx)
	return err
}

// DeleteGoal converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteGoal(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "goal_id" -------------
	var goalId GoalId

	err = runtime.BindStyledParameterWithOptions("simple", "goal_id", ctx.Param("goal_id"), &goalId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter goal_id: %s", err))
	}

	ctx.Set(SessionCookieScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteGoal(ctx, goalId)
	return err
}

// GetGoal converts echo context to params.
func (w *ServerInterfaceWrapper) GetGoal(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "goal_id" -------------
	var goalId GoalId

	err = runtime.BindStyledParameterWithOptions("simple", "goal_id", ctx.Param("goal_id"), &goalId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter goal_id: %s", err))
	}

	ctx.Set(SessionCookieScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetGoal(ctx, goalId)
	return err
}

// UpdateGoal converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateGoal(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "goal_id" -------------
	var goalId GoalId

	err = runtime.BindStyledParameterWithOptions("simple", "goal_id", ctx.Param("goal_id"), &goalId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter goal_id: %s", err))
	}

	ctx.Set(SessionCookieScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateGoal(ctx, goalId)
	return err
}

// GetHealthLive converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealthLive(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHealthLive(ctx)
	return err
}

// GetHealthReady converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealthReady(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHealthReady(ctx)
	return err
}

// ListTurnovers converts echo context to params.
func (w *ServerInterfaceWrapper) ListTurnovers(ctx echo.Context) error {
	var err error

	ctx.Set(SessionCookieScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTurnoversParams
	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameter("form", true, false, "from", ctx.QueryParams(), &params.From)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter from: %s", err))
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameter("form", true, false, "to", ctx.QueryParams(), &params.To)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter to: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListTurnovers(ctx, params)
	return err
}

// CreateTurnover converts echo context to params.
func (w *ServerInterfaceWrapper) CreateTurnover(ctx echo.Context) error {
	var err error

	ctx.Set(SessionCookieScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateTurnover(ctx)
	return err
}

// DeleteTurnover converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteTurnover(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "turnover_date" -------------
	var turnoverDate TurnoverDate

	err = runtime.BindStyledParameterWithOptions("simple", "turnover_date", ctx.Param("turnover_date"), &turnoverDate, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter turnover_date: %s", err))
	}

	ctx.Set(SessionCookieScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteTurnover(ctx, turnoverDate)
	return err
}

// GetTurnover converts echo context to params.
func (w *ServerInterfaceWrapper) GetTurnover(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "turnover_date" -------------
	var turnoverDate TurnoverDate

	err = runtime.BindStyledParameterWithOptions("simple", "turnover_date", ctx.Param("turnover_date"), &turnoverDate, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter turnover_date: %s", err))
	}

	ctx.Set(SessionCookieScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTurnover(ctx, turnoverDate)
	return err
}

// UpdateTurnover converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateTurnover(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "turnover_date" -------------
	var turnoverDate TurnoverDate

	err = runtime.BindStyledParameterWithOptions("simple", "turnover_date", ctx.Param("turnover_date"), &turnoverDate, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter turnover_date: %s", err))
	}

	ctx.Set(SessionCookieScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateTurnover(ctx, turnoverDate)
	return err
}

// ListWorklogs converts echo context to params.
func (w *ServerInterfaceWrapper) ListWorklogs(ctx echo.Context) error {
	var err error

	ctx.Set(SessionCookieScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListWorklogsParams
	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameter("form", true, false, "from", ctx.QueryParams(), &params.From)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter from: %s", err))
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameter("form", true, false, "to", ctx.QueryParams(), &params.To)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter to: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListWorklogs(ctx, params)
	return err
}

// CreateWorklog converts echo context to params.
func (w *ServerInterfaceWrapper) CreateWorklog(ctx echo.Context) error {
	var err error

	ctx.Set(SessionCookieScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateWorklog(ctx)
	return err
}

// DeleteWorklog converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteWorklog(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "work_date" -------------
	var workDate WorkDate

	err = runtime.BindStyledParameterWithOptions("simple", "work_date", ctx.Param("work_date"), &workDate, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter work_date: %s", err))
	}

	ctx.Set(SessionCookieScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteWorklog(ctx, workDate)
	return err
}

// GetWorklog converts echo context to params.
func (w *ServerInterfaceWrapper) GetWorklog(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "work_date" -------------
	var workDate WorkDate

	err = runtime.BindStyledParameterWithOptions("simple", "work_date", ctx.Param("work_date"), &workDate, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter work_date: %s", err))
	}

	ctx.Set(SessionCookieScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetWorklog(ctx, workDate)
	return err
}

// UpdateWorklog converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateWorklog(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "work_date" -------------
	var workDate WorkDate

	err = runtime.BindStyledParameterWithOptions("simple", "work_date", ctx.Param("work_date"), &workDate, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter work_date: %s", err))
	}

	ctx.Set(SessionCookieScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateWorklog(ctx, workDate)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/api/admin/admins", wrapper.GetAdminAdmins)
	router.POST(baseURL+"/api/admin/admins", wrapper.PostAdminAdmin)
	router.DELETE(baseURL+"/api/admin/admins/:account_id", wrapper.DeleteAdminAdmin)
	router.PATCH(baseURL+"/api/admin/admins/:account_id", wrapper.PatchAdminAdmin)
	router.POST(baseURL+"/api/admin/admins/:account_id/reset-password", wrapper.PostAdminAdminResetPassword)
	router.GET(baseURL+"/api/admin/invitation-codes", wrapper.GetAdminInvitationCodes)
	router.POST(baseURL+"/api/admin/invitation-codes", wrapper.PostAdminInvitationCode)
	router.DELETE(baseURL+"/api/admin/invitation-codes/:invitation_id", wrapper.DeleteAdminInvitationCode)
	router.PATCH(baseURL+"/api/admin/invitation-codes/:invitation_id", wrapper.PatchAdminInvitationCode)
	router.GET(baseURL+"/api/admin/users", wrapper.GetAdminUsers)
	router.DELETE(baseURL+"/api/admin/users/:account_id", wrapper.DeleteAdminUser)
	router.POST(baseURL+"/api/admin/users/:account_id/reset-password", wrapper.PostAdminUserResetPassword)
	router.PATCH(baseURL+"/api/admin/users/:account_id/status", wrapper.PatchAdminUserStatus)
	router.GET(baseURL+"/api/auth/accounts", wrapper.GetAuthAccounts)
	router.POST(baseURL+"/api/auth/accounts/add", wrapper.PostAuthAccountsAdd)
	router.DELETE(baseURL+"/api/auth/accounts/:account_id", wrapper.DeleteAuthAccount)
	router.POST(baseURL+"/api/auth/accounts/:account_id/switch", wrapper.PostAuthAccountsSwitch)
	router.POST(baseURL+"/api/auth/change-password", wrapper.PostAuthChangePassword)
	router.GET(baseURL+"/api/auth/csrf", wrapper.GetAuthCsrf)
	router.POST(baseURL+"/api/auth/login", wrapper.PostAuthLogin)
	router.POST(baseURL+"/api/auth/logout", wrapper.PostAuthLogout)
	router.GET(baseURL+"/api/auth/me", wrapper.GetAuthMe)
	router.PATCH(baseURL+"/api/auth/me/timezone", wrapper.PatchAuthTimezone)
	router.POST(baseURL+"/api/auth/register", wrapper.PostAuthRegister)
	router.GET(baseURL+"/api/dashboard", wrapper.GetDashboard)
	router.GET(baseURL+"/api/dreams", wrapper.ListDreams)
	router.POST(baseURL+"/api/dreams", wrapper.CreateDream)
	router.DELETE(baseURL+"/api/dreams/:dream_id", wrapper.DeleteDream)
	router.GET(baseURL+"/api/dreams/:dream_id", wrapper.GetDream)
	router.PUT(baseURL+"/api/dreams/:dream_id", wrapper.UpdateDream)
	router.GET(baseURL+"/api/goals", wrapper.ListGoals)
	router.POST(baseURL+"/api/goals", wrapper.CreateGoal)
	router.DELETE(baseURL+"/api/goals/:goal_id", wrapper.DeleteGoal)
	router.GET(baseURL+"/api/goals/:goal_id", wrapper.GetGoal)
	router.PUT(baseURL+"/api/goals/:goal_id", wrapper.UpdateGoal)
	router.GET(baseURL+"/api/health/live", wrapper.GetHealthLive)
	router.GET(baseURL+"/api/health/ready", wrapper.GetHealthReady)
	router.GET(baseURL+"/api/turnover", wrapper.ListTurnovers)
	router.POST(baseURL+"/api/turnover", wrapper.CreateTurnover)
	router.DELETE(baseURL+"/api/turnover/:turnover_date", wrapper.DeleteTurnover)
	router.GET(baseURL+"/api/turnover/:turnover_date", wrapper.GetTurnover)
	router.PUT(baseURL+"/api/turnover/:turnover_date", wrapper.UpdateTurnover)
	router.GET(baseURL+"/api/worklogs", wrapper.ListWorklogs)
	router.POST(baseURL+"/api/worklogs", wrapper.CreateWorklog)
	router.DELETE(baseURL+"/api/worklogs/:work_date", wrapper.DeleteWorklog)
	router.GET(baseURL+"/api/worklogs/:work_date", wrapper.GetWorklog)
	router.PUT(baseURL+"/api/worklogs/:work_date", wrapper.UpdateWorklog)

}
