// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"github.com/labstack/echo/v4"
)

// Defines values for HealthDataChecks.
const (
	Ready       HealthDataChecks = "ready"
	Unavailable HealthDataChecks = "unavailable"
)

// Defines values for HealthDataStatus.
const (
	Ok HealthDataStatus = "ok"
)

// ErrorBody defines model for ErrorBody.
type ErrorBody struct {
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`
	Message string                  `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error     ErrorBody `json:"error"`
	RequestId string    `json:"request_id"`
}

// HealthData defines model for HealthData.
type HealthData struct {
	Checks map[string]HealthDataChecks `json:"checks"`
	Status HealthDataStatus            `json:"status"`
}

// HealthDataChecks defines model for HealthData.Checks.
type HealthDataChecks string

// HealthDataStatus defines model for HealthData.Status.
type HealthDataStatus string

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Data      HealthData `json:"data"`
	RequestId string     `json:"request_id"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Check whether the API process is live
	// (GET /api/health/live)
	GetHealthLive(ctx echo.Context) error
	// Check whether required runtime dependencies are ready
	// (GET /api/health/ready)
	GetHealthReady(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetHealthLive converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealthLive(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHealthLive(ctx)
	return err
}

// GetHealthReady converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealthReady(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHealthReady(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/api/health/live", wrapper.GetHealthLive)
	router.GET(baseURL+"/api/health/ready", wrapper.GetHealthReady)

}
