import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Archive, Check, ChevronRight, Plus } from "lucide-react";
import { useId, useMemo, useState } from "react";
import type { AuthResponse, FinanceCategory, FinanceTransaction } from "@/api/client";
import { archiveFinanceCategory, createFinanceCategory, listFinanceBudgets, listFinanceCategories, listFinanceSnapshots, listFinanceTransactions, saveFinanceBudget, saveFinanceSnapshot, saveFinanceTransaction } from "@/api/client";
import { Button } from "@/components/ui/button";
import { ConfirmDialog, Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { FormLabel, Input } from "@/components/ui/input";
import { PageHeader } from "@/components/ui/page-header";
import { Panel } from "@/components/ui/panel";
import { Sheet, SheetContent } from "@/components/ui/sheet";
import { StatusBadge } from "@/components/ui/badge";
import { MetricCard } from "@/components/ui/metric-card";
import { EmptyState, ErrorState, LoadingState } from "@/components/ui/state-block";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { businessDate } from "@/lib/date";
import { formatMoney } from "@/lib/money";
import { errorMessage } from "@/lib/utils";

type TransactionForm = { occurred_on: string; type: "INCOME" | "EXPENSE"; category_id: string; amount: string; description: string; note: string };
type Tab = "overview" | "transactions" | "budgets" | "snapshots";
const emptyTransaction = (date: string): TransactionForm => ({ occurred_on: date, type: "EXPENSE", category_id: "", amount: "", description: "", note: "" });

export function FinancePage({ authResponse }: { authResponse: AuthResponse }) {
  const account = authResponse.data.account;
  const accountId = account.id;
  const today = businessDate(account.timezone);
  const client = useQueryClient();
  const categoriesQuery = useQuery({ queryKey: ["user", accountId, "finance-categories"], queryFn: listFinanceCategories });
  const transactionsQuery = useQuery({ queryKey: ["user", accountId, "finance-transactions"], queryFn: () => listFinanceTransactions() });
  const budgetsQuery = useQuery({ queryKey: ["user", accountId, "finance-budgets"], queryFn: listFinanceBudgets });
  const snapshotsQuery = useQuery({ queryKey: ["user", accountId, "finance-snapshots"], queryFn: listFinanceSnapshots });
  const [tab, setTab] = useState<Tab>("overview");
  const [transactionOpen, setTransactionOpen] = useState(false);
  const [budgetOpen, setBudgetOpen] = useState(false);
  const [snapshotOpen, setSnapshotOpen] = useState(false);
  const [transaction, setTransaction] = useState<TransactionForm>(emptyTransaction(today));
  const [categoryName, setCategoryName] = useState("");
  const [categoryType, setCategoryType] = useState<"INCOME" | "EXPENSE">("EXPENSE");
  const [budget, setBudget] = useState({ month: `${today.slice(0, 7)}-01`, amount: "" });
  const [snapshot, setSnapshot] = useState({ date: today, kind: "SAVINGS" as "SAVINGS" | "EMERGENCY_FUND", amount: "", note: "" });
  const [removeTarget, setRemoveTarget] = useState<FinanceCategory | null>(null);
  const [notice, setNotice] = useState("");
  const [error, setError] = useState("");
  const categories = categoriesQuery.data?.data.items.filter((item) => !item.archived_at) ?? [];
  const transactions = useMemo(() => transactionsQuery.data?.data.items ?? [], [transactionsQuery.data]);
  const invalidate = (key: string) => void client.invalidateQueries({ queryKey: ["user", accountId, key] });
  const transactionMutation = useMutation({ mutationFn: () => saveFinanceTransaction(authResponse.data.csrf_token, { occurred_on: transaction.occurred_on, type: transaction.type, category_id: transaction.category_id, amount: transaction.amount, description: transaction.description.trim() || null, note: transaction.note.trim() || null, source: "MANUAL" }), onSuccess: () => { setTransaction(emptyTransaction(today)); setTransactionOpen(false); setNotice("财务流水已保存"); setError(""); invalidate("finance-transactions"); }, onError: (value) => { setError(errorMessage(value)); setNotice(""); } });
  const categoryMutation = useMutation({ mutationFn: () => createFinanceCategory(authResponse.data.csrf_token, { name: categoryName.trim(), type: categoryType }), onSuccess: () => { setCategoryName(""); setNotice("财务分类已创建"); setError(""); invalidate("finance-categories"); }, onError: (value) => { setError(errorMessage(value)); setNotice(""); } });
  const archiveMutation = useMutation({ mutationFn: () => archiveFinanceCategory(authResponse.data.csrf_token, removeTarget!.id), onSuccess: () => { setRemoveTarget(null); setNotice("财务分类已归档"); invalidate("finance-categories"); }, onError: (value) => setError(errorMessage(value)) });
  const budgetMutation = useMutation({ mutationFn: () => saveFinanceBudget(authResponse.data.csrf_token, { month: budget.month, amount: budget.amount, category_id: null }), onSuccess: () => { setBudgetOpen(false); setNotice("月度总预算已保存"); setError(""); invalidate("finance-budgets"); }, onError: (value) => { setError(errorMessage(value)); setNotice(""); } });
  const snapshotMutation = useMutation({ mutationFn: () => saveFinanceSnapshot(authResponse.data.csrf_token, { snapshot_date: snapshot.date, kind: snapshot.kind, amount: snapshot.amount, note: snapshot.note.trim() || null }), onSuccess: () => { setSnapshotOpen(false); setNotice("资金快照已保存"); setError(""); invalidate("finance-snapshots"); }, onError: (value) => { setError(errorMessage(value)); setNotice(""); } });
  const month = today.slice(0, 7);
  const summary = useMemo(() => transactions.filter((item) => item.occurred_on.startsWith(month)).reduce((result, item) => { const amount = Number(item.amount); if (item.type === "INCOME") result.income += amount; else result.expense += amount; return result; }, { income: 0, expense: 0 }), [month, transactions]);
  const currentBudget = budgetsQuery.data?.data.items.find((item) => item.month.startsWith(month));
  const budgetUsed = Math.min(100, currentBudget ? (summary.expense / Number(currentBudget.amount)) * 100 : 0);
  const primaryAction = tab === "budgets"
    ? <Button onClick={() => setBudgetOpen(true)}><Plus size={16} />新增预算</Button>
    : tab === "snapshots"
      ? <Button onClick={() => setSnapshotOpen(true)}><Plus size={16} />新增快照</Button>
      : <Button onClick={() => setTransactionOpen(true)}><Plus size={16} />新增流水</Button>;
  return <div className="finance-page space-y-6">
    <PageHeader eyebrow="经营数据" title="财务" description="查看已记录的收支、预算和资金状态，需要时再新增或编辑记录。" />
    {(notice || error) && <p role={error ? "alert" : "status"} className={`rounded-md border px-4 py-3 text-sm ${error ? "border-rose-200 bg-rose-50 text-rose-800" : "border-teal-200 bg-teal-50 text-teal-900"}`}>{error || notice}</p>}
    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
      <Tabs value={tab} onValueChange={(value) => setTab(value as Tab)}><TabsList aria-label="财务视图"><TabsTrigger value="overview">总览</TabsTrigger><TabsTrigger value="transactions">流水</TabsTrigger><TabsTrigger value="budgets">预算</TabsTrigger><TabsTrigger value="snapshots">资金快照</TabsTrigger></TabsList></Tabs>
      <div className="flex justify-end">{primaryAction}</div>
    </div>
    {tab === "overview" && (categoriesQuery.isError || transactionsQuery.isError ? <ErrorState message="财务总览暂时无法加载" onRetry={() => { void categoriesQuery.refetch(); void transactionsQuery.refetch(); }} /> : categoriesQuery.isPending || transactionsQuery.isPending ? <LoadingState label="正在加载财务总览" /> : <Overview income={summary.income} expense={summary.expense} transactions={transactions} categories={categories} budget={currentBudget ? Number(currentBudget.amount) : null} budgetUsed={budgetUsed} />)}
    {tab === "transactions" && (categoriesQuery.isError || transactionsQuery.isError ? <ErrorState message="财务流水暂时无法加载" onRetry={() => { void categoriesQuery.refetch(); void transactionsQuery.refetch(); }} /> : categoriesQuery.isPending || transactionsQuery.isPending ? <LoadingState label="正在加载财务流水" /> : <Transactions transactions={transactions} categories={categories} />)}
    {tab === "budgets" && (budgetsQuery.isError || transactionsQuery.isError ? <ErrorState message="预算数据暂时无法加载" onRetry={() => { void budgetsQuery.refetch(); void transactionsQuery.refetch(); }} /> : budgetsQuery.isPending || transactionsQuery.isPending ? <LoadingState label="正在加载预算" /> : <Budgets budgets={budgetsQuery.data?.data.items ?? []} currentBudget={currentBudget} used={summary.expense} budgetUsed={budgetUsed} />)}
    {tab === "snapshots" && (snapshotsQuery.isError ? <ErrorState message="资金快照暂时无法加载" onRetry={() => void snapshotsQuery.refetch()} /> : snapshotsQuery.isPending ? <LoadingState label="正在加载资金快照" /> : <Snapshots snapshots={snapshotsQuery.data?.data.items ?? []} />)}
    <details className="group overflow-hidden rounded-lg border border-slate-200 bg-white shadow-panel"><summary className="flex min-h-16 cursor-pointer list-none items-center gap-3 px-5 py-4 outline-none transition hover:bg-slate-50 focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-teal-600"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-teal-50 text-teal-700"><Plus size={17} aria-hidden="true" /></span><span className="min-w-0 flex-1"><span className="block font-semibold text-slate-900">管理收支分类</span><span className="mt-0.5 block text-sm font-normal text-slate-500">新增自定义分类，或归档不再使用的分类。</span></span><ChevronRight className="shrink-0 text-slate-400 transition-transform group-open:rotate-90" size={18} aria-hidden="true" /></summary><div className="grid gap-5 border-t border-slate-200 px-5 py-5 lg:grid-cols-[minmax(0,360px)_1fr]"><div className="space-y-4"><Input label="分类名称" value={categoryName} onChange={(event) => setCategoryName(event.target.value)} required /><Select label="分类类型" value={categoryType} onChange={(event) => setCategoryType(event.target.value as typeof categoryType)} required><option value="EXPENSE">支出</option><option value="INCOME">收入</option></Select><Button onClick={() => categoryMutation.mutate()} loading={categoryMutation.isPending} disabled={!categoryName.trim()}><Plus size={16} />新增分类</Button></div><div className="space-y-2">{categories.length ? categories.map((item) => <div key={item.id} className="flex items-center justify-between gap-3 border-b border-slate-100 py-2 last:border-0"><span className="text-sm font-semibold text-slate-800">{item.name} <span className="text-xs font-normal text-slate-500">{item.type === "INCOME" ? "收入" : "支出"}{item.system_default ? " · 系统" : ""}</span></span>{!item.system_default && <Button variant="icon" size="sm" aria-label={`归档分类 ${item.name}`} onClick={() => setRemoveTarget(item)}><Archive size={15} /></Button>}</div>) : <EmptyState title="暂无分类" description="先创建一个分类。" />}</div></div></details>
    <Dialog open={transactionOpen} onOpenChange={setTransactionOpen}><DialogContent><DialogHeader><DialogTitle>新增财务流水</DialogTitle><DialogDescription>金额使用人民币，收入和支出分别选择对应分类。</DialogDescription></DialogHeader><div className="space-y-4"><Input label="发生日期" type="date" value={transaction.occurred_on} onChange={(event) => setTransaction({ ...transaction, occurred_on: event.target.value })} required /><Select label="类型" value={transaction.type} onChange={(event) => setTransaction({ ...transaction, type: event.target.value as TransactionForm["type"], category_id: "" })} required><option value="EXPENSE">支出</option><option value="INCOME">收入</option></Select><Select label="分类" value={transaction.category_id} onChange={(event) => setTransaction({ ...transaction, category_id: event.target.value })} required><option value="">请选择分类</option>{categories.filter((item) => item.type === transaction.type).map((item) => <option key={item.id} value={item.id}>{item.name}{item.system_default ? "（系统）" : ""}</option>)}</Select><Input label="金额" type="number" min="0" step="0.01" value={transaction.amount} onChange={(event) => setTransaction({ ...transaction, amount: event.target.value })} required /><Input label="摘要" value={transaction.description} onChange={(event) => setTransaction({ ...transaction, description: event.target.value })} /><Input label="备注" value={transaction.note} onChange={(event) => setTransaction({ ...transaction, note: event.target.value })} /></div><div className="mt-6 flex justify-end gap-3"><Button variant="secondary" onClick={() => setTransactionOpen(false)} disabled={transactionMutation.isPending}>取消</Button><Button onClick={() => transactionMutation.mutate()} loading={transactionMutation.isPending} disabled={!transaction.category_id || !transaction.amount}><Check size={16} />保存流水</Button></div></DialogContent></Dialog>
    <Sheet open={budgetOpen} onOpenChange={setBudgetOpen}><SheetContent title="新增月度预算" description="预算仅保存当前账号的月度总额。" footer={<div className="flex justify-end"><Button onClick={() => budgetMutation.mutate()} loading={budgetMutation.isPending} disabled={!budget.amount}><Check size={16} />保存预算</Button></div>}><div className="space-y-4"><Input label="月份" type="month" value={budget.month.slice(0, 7)} onChange={(event) => setBudget({ ...budget, month: `${event.target.value}-01` })} required /><Input label="预算金额" type="number" min="0" step="0.01" value={budget.amount} onChange={(event) => setBudget({ ...budget, amount: event.target.value })} required /></div></SheetContent></Sheet>
    <Sheet open={snapshotOpen} onOpenChange={setSnapshotOpen}><SheetContent title="新增资金快照" description="记录某个日期的储蓄或应急资金状态。" footer={<div className="flex justify-end"><Button onClick={() => snapshotMutation.mutate()} loading={snapshotMutation.isPending} disabled={!snapshot.amount}><Check size={16} />保存快照</Button></div>}><div className="space-y-4"><Input label="快照日期" type="date" value={snapshot.date} onChange={(event) => setSnapshot({ ...snapshot, date: event.target.value })} required /><Select label="快照类型" value={snapshot.kind} onChange={(event) => setSnapshot({ ...snapshot, kind: event.target.value as typeof snapshot.kind })} required><option value="SAVINGS">储蓄</option><option value="EMERGENCY_FUND">应急资金</option></Select><Input label="金额" type="number" min="0" step="0.01" value={snapshot.amount} onChange={(event) => setSnapshot({ ...snapshot, amount: event.target.value })} required /><Input label="备注" value={snapshot.note} onChange={(event) => setSnapshot({ ...snapshot, note: event.target.value })} /></div></SheetContent></Sheet>
    <ConfirmDialog open={Boolean(removeTarget)} onOpenChange={(open) => !open && setRemoveTarget(null)} title="确认归档分类" description={removeTarget ? `确定归档“${removeTarget.name}”吗？归档后不能用于新流水。` : ""} confirmLabel="归档" loading={archiveMutation.isPending} onConfirm={() => archiveMutation.mutate()} />
  </div>;
}

function Overview({ income, expense, transactions, categories, budget, budgetUsed }: { income: number; expense: number; transactions: FinanceTransaction[]; categories: FinanceCategory[]; budget: number | null; budgetUsed: number }) {
  const categoryTotals = categories.map((category) => ({ name: category.name, amount: transactions.filter((item) => item.category_id === category.id && item.type === "EXPENSE").reduce((total, item) => total + Number(item.amount), 0) })).filter((item) => item.amount > 0).sort((a, b) => b.amount - a.amount).slice(0, 5);
  return <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-3"><Metric label="本月收入" value={formatMoney(income.toFixed(2))} tone="success" /><Metric label="本月支出" value={formatMoney(expense.toFixed(2))} tone="warning" /><Metric label="本月净现金流" value={formatMoney((income - expense).toFixed(2))} tone={income >= expense ? "success" : "danger"} /></div><div className="grid gap-5 lg:grid-cols-[1.15fr_0.85fr]"><Panel title="预算使用情况" description="按当前月份的真实支出计算。">{budget === null ? <EmptyState title="本月还没有预算" description="在预算视图中保存一个月度总预算。" /> : <div><div className="flex items-end justify-between gap-4"><div><p className="text-3xl font-bold text-slate-950">{formatMoney(expense.toFixed(2))}</p><p className="mt-1 text-sm text-slate-500">已使用 / {formatMoney(budget.toFixed(2))}</p></div><span className="text-sm font-semibold text-teal-700">{Math.round(budgetUsed)}%</span></div><div className="mt-5 h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-teal-600" style={{ width: `${budgetUsed}%` }} /></div></div>}</Panel><Panel title="支出分类" description="仅显示当前月份有记录的分类。">{categoryTotals.length ? <div className="space-y-3">{categoryTotals.map((item) => <div key={item.name} className="flex items-center justify-between border-b border-slate-100 pb-2 text-sm last:border-0"><span>{item.name}</span><strong>{formatMoney(item.amount.toFixed(2))}</strong></div>)}</div> : <EmptyState title="暂无支出分类" description="保存支出流水后，这里会显示结构。" />}</Panel></div><Panel title="最近流水" description="按发生日期倒序展示最近 8 条。"><TransactionTable transactions={transactions.slice(0, 8)} categories={categories} /></Panel></div>;
}
function Transactions({ transactions, categories }: { transactions: FinanceTransaction[]; categories: FinanceCategory[] }) { return <Panel title="流水列表" description="查看当前账号的经营流水，新增操作从右上角开始。">{transactions.length ? <TransactionTable transactions={transactions} categories={categories} /> : <EmptyState title="暂无流水" description="使用页面右上角新增第一条流水。" />}</Panel>; }
function Budgets({ budgets, currentBudget, used, budgetUsed }: { budgets: { id: string; month: string; amount: string }[]; currentBudget?: { amount: string }; used: number; budgetUsed: number }) { return <Panel title="月度预算" description="按月份保存总预算，历史记录保留在列表中。"><div className="grid gap-5 lg:grid-cols-[minmax(0,360px)_1fr]"><div className="rounded-lg border border-teal-200 bg-teal-50 p-5"><p className="text-sm font-semibold text-teal-900">当前月预算</p>{currentBudget ? <><p className="mt-3 text-2xl font-bold text-slate-950">{formatMoney(currentBudget.amount)}</p><p className="mt-1 text-sm text-slate-600">已用 {formatMoney(used.toFixed(2))} · {Math.round(budgetUsed)}%</p></> : <p className="mt-3 text-sm text-slate-600">还没有当前月预算。</p>}</div>{budgets.length ? <div className="overflow-x-auto"><table className="min-w-[420px] w-full text-left text-sm"><thead className="border-b border-slate-200 text-xs text-slate-500"><tr><th className="px-3 py-2">月份</th><th className="px-3 py-2">预算</th></tr></thead><tbody>{budgets.map((item) => <tr key={item.id} className="border-b border-slate-100"><td className="px-3 py-3">{item.month}</td><td className="px-3 py-3 font-semibold">{formatMoney(item.amount)}</td></tr>)}</tbody></table></div> : <EmptyState title="暂无历史预算" description="使用页面右上角新增第一个月度预算。" />}</div></Panel>; }
function Snapshots({ snapshots }: { snapshots: { id: string; snapshot_date: string; kind: string; amount: string; note?: string | null }[] }) { return <Panel title="资金快照" description="记录储蓄和应急资金的时间点状态。">{snapshots.length ? <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{snapshots.map((item) => <div key={item.id} className="rounded-lg border border-slate-200 p-4"><div className="flex items-center justify-between gap-3"><span className="text-sm font-semibold text-slate-700">{item.kind === "SAVINGS" ? "储蓄" : "应急资金"}</span><StatusBadge tone="info">{item.snapshot_date}</StatusBadge></div><p className="mt-4 text-2xl font-bold text-slate-950">{formatMoney(item.amount)}</p>{item.note && <p className="mt-2 text-sm text-slate-500">{item.note}</p>}</div>)}</div> : <EmptyState title="暂无资金快照" description="使用页面右上角保存一条当前资金状态。" />}</Panel>; }
function TransactionTable({ transactions, categories }: { transactions: FinanceTransaction[]; categories: FinanceCategory[] }) { return <div className="overflow-x-auto"><table className="min-w-[620px] w-full text-left text-sm"><thead className="border-b border-slate-200 text-xs text-slate-500"><tr><th className="px-3 py-2">日期</th><th className="px-3 py-2">类型</th><th className="px-3 py-2">分类</th><th className="px-3 py-2">金额</th><th className="px-3 py-2">摘要</th></tr></thead><tbody>{transactions.map((item) => <tr key={item.id} className="border-b border-slate-100 last:border-0 hover:bg-slate-50"><td className="px-3 py-3">{item.occurred_on}</td><td className="px-3 py-3"><StatusBadge tone={item.type === "INCOME" ? "success" : "warning"}>{item.type === "INCOME" ? "收入" : "支出"}</StatusBadge></td><td className="px-3 py-3">{categories.find((category) => category.id === item.category_id)?.name ?? "未命名"}</td><td className="px-3 py-3 font-semibold">{formatMoney(item.amount)}</td><td className="px-3 py-3 text-slate-600">{item.description ?? item.note ?? "-"}</td></tr>)}</tbody></table></div>; }
function Metric({ label, value, tone }: { label: string; value: string; tone: "success" | "warning" | "danger" }) { return <MetricCard label={label} value={value} tone={tone === "success" ? "brand" : tone === "warning" ? "amber" : "coral"} />; }
function Select({ label, children, required, ...props }: { label: string; children: React.ReactNode } & React.SelectHTMLAttributes<HTMLSelectElement>) { const selectId = useId(); return <div className="block space-y-1.5"><FormLabel htmlFor={selectId} required={required}>{label}</FormLabel><select id={selectId} className="min-h-10 w-full rounded-md border border-slate-300 bg-white px-3 text-sm focus:border-teal-600 focus:outline-none focus:ring-2 focus:ring-teal-100" required={required} {...props}>{children}</select></div>; }
