/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check whether the API process is live */
        get: operations["getHealthLive"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check whether required runtime dependencies are ready */
        get: operations["getHealthReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a normal user with an invitation code */
        post: operations["postAuthRegister"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in an account */
        post: operations["postAuthLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End the current browser session */
        post: operations["postAuthLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the CSRF token for the current browser session */
        get: operations["getAuthCsrf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the active account */
        get: operations["getAuthMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change the active account password */
        post: operations["postAuthChangePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me/timezone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change the active account timezone */
        patch: operations["patchAuthTimezone"];
        trace?: never;
    };
    "/api/auth/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List normal accounts linked to this browser session */
        get: operations["getAuthAccounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/accounts/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate and add another normal account to this browser session */
        post: operations["postAuthAccountsAdd"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/accounts/{account_id}/switch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Switch the active normal account without re-entering its password */
        post: operations["postAuthAccountsSwitch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/accounts/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a linked normal account from this browser session */
        delete: operations["deleteAuthAccount"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List normal users without business data */
        get: operations["getAdminUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{account_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Enable or disable a normal user */
        patch: operations["patchAdminUserStatus"];
        trace?: never;
    };
    "/api/admin/users/{account_id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset a normal user password */
        post: operations["postAdminUserResetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a normal user and its online access */
        delete: operations["deleteAdminUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/invitation-codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List invitation codes */
        get: operations["getAdminInvitationCodes"];
        put?: never;
        /** Create an invitation code */
        post: operations["postAdminInvitationCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/invitation-codes/{invitation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Disable an invitation code */
        delete: operations["deleteAdminInvitationCode"];
        options?: never;
        head?: never;
        /** Update invitation status or limits */
        patch: operations["patchAdminInvitationCode"];
        trace?: never;
    };
    "/api/admin/admins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List ordinary administrators */
        get: operations["getAdminAdmins"];
        put?: never;
        /** Create an ordinary administrator */
        post: operations["postAdminAdmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/admins/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an ordinary administrator */
        delete: operations["deleteAdminAdmin"];
        options?: never;
        head?: never;
        /** Enable or disable an ordinary administrator */
        patch: operations["patchAdminAdmin"];
        trace?: never;
    };
    "/api/admin/admins/{account_id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset an ordinary administrator password */
        post: operations["postAdminAdminResetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthData: {
            /** @enum {string} */
            status: "ok";
            checks: {
                [key: string]: "ready" | "unavailable";
            };
        };
        HealthResponse: {
            data: components["schemas"]["HealthData"];
            request_id: string;
        };
        ErrorBody: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
            request_id: string;
        };
        Account: {
            /** Format: uuid */
            id: string;
            username: string;
            /** @enum {string} */
            role: "USER" | "ADMIN" | "SUPER_ADMIN";
            /** @enum {string} */
            status: "ACTIVE" | "DISABLED";
            timezone: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_login_at?: string | null;
        };
        SessionAccount: components["schemas"]["Account"] & {
            active: boolean;
        };
        RegisterRequest: {
            username: string;
            password: string;
            invitation_code: string;
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        ChangePasswordRequest: {
            current_password: string;
            new_password: string;
        };
        TimezoneRequest: {
            timezone: string;
        };
        StatusRequest: {
            /** @enum {string} */
            status: "ACTIVE" | "DISABLED";
        };
        ResetPasswordRequest: {
            temporary_password?: string;
        };
        CreateAdminRequest: {
            username: string;
            password: string;
        };
        CreateInvitationRequest: {
            code?: string;
            max_uses?: number | null;
            /** Format: date-time */
            expires_at?: string | null;
        };
        UpdateInvitationRequest: {
            /** @enum {string} */
            status?: "ACTIVE" | "DISABLED";
            max_uses?: number | null;
            /** Format: date-time */
            expires_at?: string | null;
            /**
             * @description Clear max_uses and make the code unlimited.
             * @default false
             */
            clear_max_uses: boolean;
            /**
             * @description Clear expires_at and make the code non-expiring.
             * @default false
             */
            clear_expires_at: boolean;
        };
        AuthData: {
            account: components["schemas"]["Account"];
            csrf_token: string;
            accounts: components["schemas"]["SessionAccount"][];
        };
        AuthResponse: {
            data: components["schemas"]["AuthData"];
            request_id: string;
        };
        CsrfData: {
            csrf_token: string;
        };
        CsrfResponse: {
            data: components["schemas"]["CsrfData"];
            request_id: string;
        };
        AccountsData: {
            account: components["schemas"]["Account"];
            accounts: components["schemas"]["SessionAccount"][];
            csrf_token: string;
        };
        AccountsResponse: {
            data: components["schemas"]["AccountsData"];
            request_id: string;
        };
        AccountResponse: {
            data: components["schemas"]["Account"];
            request_id: string;
        };
        PaginationMeta: {
            page: number;
            page_size: number;
            total: number;
        };
        AccountsListData: {
            items: components["schemas"]["Account"][];
        };
        AccountsListResponse: {
            data: components["schemas"]["AccountsListData"];
            meta: components["schemas"]["PaginationMeta"];
            request_id: string;
        };
        ResetPasswordData: {
            temporary_password: string;
        };
        ResetPasswordResponse: {
            data: components["schemas"]["ResetPasswordData"];
            request_id: string;
        };
        Invitation: {
            /** Format: uuid */
            id: string;
            code: string;
            /** @enum {string} */
            status: "ACTIVE" | "DISABLED";
            max_uses?: number | null;
            used_count: number;
            /** Format: date-time */
            expires_at?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        InvitationListResponse: {
            data: {
                items: components["schemas"]["Invitation"][];
            };
            request_id: string;
        };
        InvitationResponse: {
            data: components["schemas"]["Invitation"];
            request_id: string;
        };
    };
    responses: {
        /** @description Request failed */
        ErrorResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        AccountId: string;
        InvitationId: string;
        Page: number;
        PageSize: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthLive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API process is live */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getHealthReady: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dependencies are ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description One or more dependencies are unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postAuthRegister: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description User registered and signed in */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    postAuthLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Account signed in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    postAuthLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session ended */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getAuthCsrf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSRF token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsrfResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getAuthMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    postAuthChangePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed and sessions invalidated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    patchAuthTimezone: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TimezoneRequest"];
            };
        };
        responses: {
            /** @description Updated active account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getAuthAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Linked accounts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountsResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    postAuthAccountsAdd: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Account added */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountsResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    postAuthAccountsSwitch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active account switched */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    deleteAuthAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account unlinked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getAdminUsers: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountsListResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    patchAdminUserStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusRequest"];
            };
        };
        responses: {
            /** @description Updated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    postAdminUserResetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Temporary password result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetPasswordResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    deleteAdminUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getAdminInvitationCodes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invitation list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationListResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    postAdminInvitationCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInvitationRequest"];
            };
        };
        responses: {
            /** @description Invitation created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    deleteAdminInvitationCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invitation_id: components["parameters"]["InvitationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invitation disabled */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    patchAdminInvitationCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invitation_id: components["parameters"]["InvitationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateInvitationRequest"];
            };
        };
        responses: {
            /** @description Updated invitation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getAdminAdmins: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Administrator list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountsListResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    postAdminAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAdminRequest"];
            };
        };
        responses: {
            /** @description Administrator created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    deleteAdminAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Administrator deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    patchAdminAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusRequest"];
            };
        };
        responses: {
            /** @description Updated administrator */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    postAdminAdminResetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Temporary password result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetPasswordResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
}
