/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check whether the API process is live */
        get: operations["getHealthLive"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check whether required runtime dependencies are ready */
        get: operations["getHealthReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a normal user with an invitation code */
        post: operations["postAuthRegister"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in an account */
        post: operations["postAuthLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End the current browser session */
        post: operations["postAuthLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the CSRF token for the current browser session */
        get: operations["getAuthCsrf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the active account */
        get: operations["getAuthMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change the active account password */
        post: operations["postAuthChangePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me/timezone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change the active account timezone */
        patch: operations["patchAuthTimezone"];
        trace?: never;
    };
    "/api/auth/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List normal accounts linked to this browser session */
        get: operations["getAuthAccounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/accounts/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate and add another normal account to this browser session */
        post: operations["postAuthAccountsAdd"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/accounts/{account_id}/switch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Switch the active normal account without re-entering its password */
        post: operations["postAuthAccountsSwitch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/accounts/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a linked normal account from this browser session */
        delete: operations["deleteAuthAccount"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List normal users without business data */
        get: operations["getAdminUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{account_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Enable or disable a normal user */
        patch: operations["patchAdminUserStatus"];
        trace?: never;
    };
    "/api/admin/users/{account_id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset a normal user password */
        post: operations["postAdminUserResetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a normal user and its online access */
        delete: operations["deleteAdminUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/invitation-codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List invitation codes */
        get: operations["getAdminInvitationCodes"];
        put?: never;
        /** Create an invitation code */
        post: operations["postAdminInvitationCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/invitation-codes/{invitation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Disable an invitation code */
        delete: operations["deleteAdminInvitationCode"];
        options?: never;
        head?: never;
        /** Update invitation status or limits */
        patch: operations["patchAdminInvitationCode"];
        trace?: never;
    };
    "/api/admin/admins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List ordinary administrators */
        get: operations["getAdminAdmins"];
        put?: never;
        /** Create an ordinary administrator */
        post: operations["postAdminAdmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/admins/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an ordinary administrator */
        delete: operations["deleteAdminAdmin"];
        options?: never;
        head?: never;
        /** Enable or disable an ordinary administrator */
        patch: operations["patchAdminAdmin"];
        trace?: never;
    };
    "/api/admin/admins/{account_id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset an ordinary administrator password */
        post: operations["postAdminAdminResetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the user dashboard aggregates for a business date */
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/worklogs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List daily worklogs in a business-date range */
        get: operations["listWorklogs"];
        put?: never;
        /** Create or replace a daily worklog */
        post: operations["createWorklog"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/worklogs/{work_date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a daily worklog */
        get: operations["getWorklog"];
        /** Replace a daily worklog */
        put: operations["updateWorklog"];
        post?: never;
        /** Delete a daily worklog */
        delete: operations["deleteWorklog"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/turnover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List daily turnovers in a business-date range */
        get: operations["listTurnovers"];
        put?: never;
        /** Create or replace a daily turnover */
        post: operations["createTurnover"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/turnover/{turnover_date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get turnover for a business date */
        get: operations["getTurnover"];
        /** Replace turnover for a business date */
        put: operations["updateTurnover"];
        post?: never;
        /** Delete turnover for a business date */
        delete: operations["deleteTurnover"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dreams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List dreams for the current user */
        get: operations["listDreams"];
        put?: never;
        /** Create a dream */
        post: operations["createDream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dreams/{dream_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a dream */
        get: operations["getDream"];
        /** Replace a dream */
        put: operations["updateDream"];
        post?: never;
        /** Delete a dream */
        delete: operations["deleteDream"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List goals with calculated progress */
        get: operations["listGoals"];
        put?: never;
        /** Create a goal */
        post: operations["createGoal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/goals/{goal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a goal with calculated progress */
        get: operations["getGoal"];
        /** Replace a goal */
        put: operations["updateGoal"];
        post?: never;
        /** Delete a goal and its descendants */
        delete: operations["deleteGoal"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calendar/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List expanded calendar event occurrences in a time range */
        get: operations["listCalendarEvents"];
        put?: never;
        /** Create a one-time or recurring calendar event */
        post: operations["createCalendarEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calendar/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a calendar event series */
        get: operations["getCalendarEvent"];
        /** Update an entire series, one occurrence, or an occurrence and following events */
        put: operations["updateCalendarEvent"];
        post?: never;
        /** Delete a calendar event series and send cancellation notices */
        delete: operations["deleteCalendarEvent"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List saved daily, weekly, or monthly reviews */
        get: operations["listReviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{review_type}/{period_start}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a review and its live period totals */
        get: operations["getReview"];
        /** Create or update one review for its period */
        put: operations["updateReview"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/worklogs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregate worklogs by day, week, or month */
        get: operations["getWorklogAnalytics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/turnover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregate turnover by day, week, or month */
        get: operations["getTurnoverAnalytics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregate goals by their business start date */
        get: operations["getGoalAnalytics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthData: {
            /** @enum {string} */
            status: "ok";
            checks: {
                [key: string]: "ready" | "unavailable";
            };
        };
        HealthResponse: {
            data: components["schemas"]["HealthData"];
            request_id: string;
        };
        ErrorBody: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
            request_id: string;
        };
        Account: {
            /** Format: uuid */
            id: string;
            username: string;
            /** @enum {string} */
            role: "USER" | "ADMIN" | "SUPER_ADMIN";
            /** @enum {string} */
            status: "ACTIVE" | "DISABLED";
            timezone: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_login_at?: string | null;
        };
        SessionAccount: components["schemas"]["Account"] & {
            active: boolean;
        };
        RegisterRequest: {
            username: string;
            password: string;
            invitation_code: string;
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        ChangePasswordRequest: {
            current_password: string;
            new_password: string;
        };
        TimezoneRequest: {
            timezone: string;
        };
        StatusRequest: {
            /** @enum {string} */
            status: "ACTIVE" | "DISABLED";
        };
        ResetPasswordRequest: {
            temporary_password?: string;
        };
        CreateAdminRequest: {
            username: string;
            password: string;
        };
        CreateInvitationRequest: {
            code?: string;
            max_uses?: number | null;
            /** Format: date-time */
            expires_at?: string | null;
        };
        UpdateInvitationRequest: {
            /** @enum {string} */
            status?: "ACTIVE" | "DISABLED";
            max_uses?: number | null;
            /** Format: date-time */
            expires_at?: string | null;
            /**
             * @description Clear max_uses and make the code unlimited.
             * @default false
             */
            clear_max_uses: boolean;
            /**
             * @description Clear expires_at and make the code non-expiring.
             * @default false
             */
            clear_expires_at: boolean;
        };
        AuthData: {
            account: components["schemas"]["Account"];
            csrf_token: string;
            accounts: components["schemas"]["SessionAccount"][];
        };
        AuthResponse: {
            data: components["schemas"]["AuthData"];
            request_id: string;
        };
        CsrfData: {
            csrf_token: string;
        };
        CsrfResponse: {
            data: components["schemas"]["CsrfData"];
            request_id: string;
        };
        AccountsData: {
            account: components["schemas"]["Account"];
            accounts: components["schemas"]["SessionAccount"][];
            csrf_token: string;
        };
        AccountsResponse: {
            data: components["schemas"]["AccountsData"];
            request_id: string;
        };
        AccountResponse: {
            data: components["schemas"]["Account"];
            request_id: string;
        };
        PaginationMeta: {
            page: number;
            page_size: number;
            total: number;
        };
        AccountsListData: {
            items: components["schemas"]["Account"][];
        };
        AccountsListResponse: {
            data: components["schemas"]["AccountsListData"];
            meta: components["schemas"]["PaginationMeta"];
            request_id: string;
        };
        ResetPasswordData: {
            temporary_password: string;
        };
        ResetPasswordResponse: {
            data: components["schemas"]["ResetPasswordData"];
            request_id: string;
        };
        Invitation: {
            /** Format: uuid */
            id: string;
            code: string;
            /** @enum {string} */
            status: "ACTIVE" | "DISABLED";
            max_uses?: number | null;
            used_count: number;
            /** Format: date-time */
            expires_at?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        InvitationListResponse: {
            data: {
                items: components["schemas"]["Invitation"][];
            };
            request_id: string;
        };
        InvitationResponse: {
            data: components["schemas"]["Invitation"];
            request_id: string;
        };
        Worklog: {
            /** Format: uuid */
            id: string;
            /** Format: date */
            work_date: string;
            open_conversation_count: number;
            deep_conversation_count: number;
            buffer_count: number;
            story_share_count: number;
            screening_count: number;
            opportunity_count: number;
            meeting_count: number;
            customer_followup_count: number;
            reading_minutes: number;
            audio_minutes: number;
            turnover_pv?: number | null;
            turnover_net_amount?: number | null;
            note?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        WorklogRequest: {
            /** Format: date */
            work_date: string;
            open_conversation_count: number;
            deep_conversation_count: number;
            buffer_count: number;
            story_share_count: number;
            screening_count: number;
            opportunity_count: number;
            meeting_count: number;
            customer_followup_count: number;
            /** @default 0 */
            reading_minutes: number;
            /** @default 0 */
            audio_minutes: number;
            turnover_pv?: number | null;
            turnover_net_amount?: number | null;
            note?: string | null;
        };
        WorklogResponse: {
            data: components["schemas"]["Worklog"];
            request_id: string;
        };
        WorklogListResponse: {
            data: {
                items: components["schemas"]["Worklog"][];
            };
            request_id: string;
        };
        Turnover: {
            /** Format: uuid */
            id: string;
            /** Format: date */
            turnover_date: string;
            pv: number;
            net_amount: number;
            note?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        TurnoverRequest: {
            /** Format: date */
            turnover_date: string;
            pv?: number | null;
            net_amount?: number | null;
            note?: string | null;
        };
        TurnoverResponse: {
            data: components["schemas"]["Turnover"];
            request_id: string;
        };
        TurnoverListResponse: {
            data: {
                items: components["schemas"]["Turnover"][];
            };
            request_id: string;
        };
        Dream: {
            /** Format: uuid */
            id: string;
            title: string;
            description?: string | null;
            goal_ids: string[];
            sort_order: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        DreamRequest: {
            title: string;
            description?: string | null;
            goal_ids?: string[];
            /** @default 0 */
            sort_order: number;
        };
        DreamResponse: {
            data: components["schemas"]["Dream"];
            request_id: string;
        };
        DreamListResponse: {
            data: {
                items: components["schemas"]["Dream"][];
            };
            request_id: string;
        };
        GoalMetric: {
            /** @enum {string} */
            metric_code: "conversation_open_count" | "deep_conversation_count" | "buffer_count" | "story_share_count" | "screening_count" | "opportunity_count" | "meeting_count" | "customer_followup_count" | "reading_minutes" | "audio_minutes" | "turnover_pv" | "turnover_net_amount";
            target_value: number;
            unit: string;
            actual_value: number;
            progress: number;
        };
        Goal: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            parent_id?: string | null;
            /** @enum {string} */
            type: "LONG_TERM" | "YEAR" | "STAGE" | "MONTH" | "WEEK" | "DAY";
            title: string;
            description?: string | null;
            /** Format: date */
            start_date?: string | null;
            /** Format: date */
            due_date?: string | null;
            /** @enum {string} */
            status: "NOT_STARTED" | "IN_PROGRESS" | "COMPLETED" | "PAUSED" | "CANCELLED";
            sort_order: number;
            metrics: components["schemas"]["GoalMetric"][];
            progress: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        GoalRequest: {
            /** Format: uuid */
            parent_id?: string | null;
            /** @enum {string} */
            type: "LONG_TERM" | "YEAR" | "STAGE" | "MONTH" | "WEEK" | "DAY";
            title: string;
            description?: string | null;
            /** Format: date */
            start_date?: string | null;
            /** Format: date */
            due_date?: string | null;
            /**
             * @default NOT_STARTED
             * @enum {string}
             */
            status: "NOT_STARTED" | "IN_PROGRESS" | "COMPLETED" | "PAUSED" | "CANCELLED";
            /** @default 0 */
            sort_order: number;
            metrics?: {
                /** @enum {string} */
                metric_code: "conversation_open_count" | "deep_conversation_count" | "buffer_count" | "story_share_count" | "screening_count" | "opportunity_count" | "meeting_count" | "customer_followup_count" | "reading_minutes" | "audio_minutes" | "turnover_pv" | "turnover_net_amount";
                target_value: number;
                unit: string;
            }[];
        };
        GoalResponse: {
            data: components["schemas"]["Goal"];
            request_id: string;
        };
        GoalListResponse: {
            data: {
                items: components["schemas"]["Goal"][];
            };
            request_id: string;
        };
        WorklogTotals: {
            open_conversation_count: number;
            deep_conversation_count: number;
            buffer_count: number;
            story_share_count: number;
            screening_count: number;
            opportunity_count: number;
            meeting_count: number;
            customer_followup_count: number;
            reading_minutes: number;
            audio_minutes: number;
        };
        TurnoverTotals: {
            pv: number;
            net_amount: number;
        };
        DashboardPeriod: {
            /** Format: date */
            from: string;
            /** Format: date */
            to: string;
            worklogs: components["schemas"]["WorklogTotals"];
            turnover: components["schemas"]["TurnoverTotals"];
        };
        DashboardData: {
            /** Format: date */
            date: string;
            today: components["schemas"]["DashboardPeriod"];
            week: components["schemas"]["DashboardPeriod"];
            month: components["schemas"]["DashboardPeriod"];
            active_goals: components["schemas"]["Goal"][];
            dreams_count: number;
        };
        DashboardResponse: {
            data: components["schemas"]["DashboardData"];
            request_id: string;
        };
        CalendarAttendee: {
            /** Format: email */
            email: string;
            display_name?: string | null;
        };
        CalendarEvent: {
            /** Format: uuid */
            id: string;
            occurrence_id: string;
            uid: string;
            sequence: number;
            title: string;
            description?: string | null;
            location_or_link?: string | null;
            timezone: string;
            all_day: boolean;
            /** Format: date-time */
            start_at: string;
            /** Format: date-time */
            end_at: string;
            /** @enum {string} */
            recurrence_freq: "NONE" | "DAILY" | "WEEKLY" | "MONTHLY" | "YEARLY";
            recurrence_interval: number;
            recurrence_weekdays: number[];
            /** @enum {string} */
            recurrence_end_type: "NEVER" | "UNTIL" | "COUNT";
            /** Format: date-time */
            recurrence_until?: string | null;
            recurrence_count?: number | null;
            /** Format: date-time */
            original_occurrence_start?: string | null;
            is_exception?: boolean;
            attendees: components["schemas"]["CalendarAttendee"][];
        };
        CalendarEventRequest: {
            title: string;
            description?: string | null;
            location_or_link?: string | null;
            timezone: string;
            /** @default false */
            all_day: boolean;
            /** Format: date-time */
            start_at: string;
            /** Format: date-time */
            end_at: string;
            /**
             * @default NONE
             * @enum {string}
             */
            recurrence_freq: "NONE" | "DAILY" | "WEEKLY" | "MONTHLY" | "YEARLY";
            /** @default 1 */
            recurrence_interval: number;
            recurrence_weekdays?: number[];
            /**
             * @default NEVER
             * @enum {string}
             */
            recurrence_end_type: "NEVER" | "UNTIL" | "COUNT";
            /** Format: date-time */
            recurrence_until?: string | null;
            recurrence_count?: number | null;
            attendees?: components["schemas"]["CalendarAttendee"][];
            /**
             * @default SERIES
             * @enum {string}
             */
            edit_scope: "SERIES" | "THIS_ONLY" | "THIS_AND_FOLLOWING";
            /** Format: date-time */
            occurrence_start?: string | null;
        };
        CalendarEventResponse: {
            data: components["schemas"]["CalendarEvent"];
            request_id: string;
        };
        CalendarEventListResponse: {
            data: {
                items: components["schemas"]["CalendarEvent"][];
            };
            request_id: string;
        };
        ReviewPeriodTotals: {
            worklog_action_count: number;
            turnover_pv: number;
            turnover_net_amount: number;
        };
        Review: {
            /** Format: uuid */
            id?: string | null;
            /** @enum {string} */
            type: "DAILY" | "WEEKLY" | "MONTHLY";
            /** Format: date */
            period_start: string;
            good: string;
            problems: string;
            improvements: string;
            next_focus: string;
            summary?: string | null;
            totals: components["schemas"]["ReviewPeriodTotals"];
        };
        ReviewRequest: {
            good?: string;
            problems?: string;
            improvements?: string;
            next_focus?: string;
            summary?: string | null;
        };
        ReviewResponse: {
            data: components["schemas"]["Review"];
            request_id: string;
        };
        ReviewListResponse: {
            data: {
                items: components["schemas"]["Review"][];
            };
            request_id: string;
        };
        AnalyticsBucket: {
            period: string;
            action_count: number;
            reading_minutes: number;
            audio_minutes: number;
            pv: number;
            net_amount: number;
            goal_count: number;
            completed_count: number;
        };
        AnalyticsData: {
            metric: string;
            /** Format: date */
            from: string;
            /** Format: date */
            to: string;
            /** @enum {string} */
            granularity: "day" | "week" | "month";
            buckets: components["schemas"]["AnalyticsBucket"][];
        };
        AnalyticsResponse: {
            data: components["schemas"]["AnalyticsData"];
            request_id: string;
        };
    };
    responses: {
        /** @description Request failed */
        ErrorResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        AccountId: string;
        InvitationId: string;
        Page: number;
        PageSize: number;
        BusinessDate: string;
        DateFrom: string;
        DateTo: string;
        WorkDate: string;
        TurnoverDate: string;
        DreamId: string;
        GoalId: string;
        CalendarEventId: string;
        CalendarFrom: string;
        CalendarTo: string;
        ReviewType: "DAILY" | "WEEKLY" | "MONTHLY";
        ReviewPeriodStart: string;
        AnalyticsGranularity: "day" | "week" | "month";
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthLive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API process is live */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getHealthReady: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dependencies are ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description One or more dependencies are unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postAuthRegister: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description User registered and signed in */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    postAuthLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Account signed in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    postAuthLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session ended */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getAuthCsrf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSRF token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsrfResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getAuthMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    postAuthChangePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed and sessions invalidated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    patchAuthTimezone: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TimezoneRequest"];
            };
        };
        responses: {
            /** @description Updated active account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getAuthAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Linked accounts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountsResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    postAuthAccountsAdd: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Account added */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountsResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    postAuthAccountsSwitch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active account switched */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    deleteAuthAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account unlinked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getAdminUsers: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountsListResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    patchAdminUserStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusRequest"];
            };
        };
        responses: {
            /** @description Updated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    postAdminUserResetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Temporary password result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetPasswordResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    deleteAdminUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getAdminInvitationCodes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invitation list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationListResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    postAdminInvitationCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInvitationRequest"];
            };
        };
        responses: {
            /** @description Invitation created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    deleteAdminInvitationCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invitation_id: components["parameters"]["InvitationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invitation disabled */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    patchAdminInvitationCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invitation_id: components["parameters"]["InvitationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateInvitationRequest"];
            };
        };
        responses: {
            /** @description Updated invitation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getAdminAdmins: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Administrator list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountsListResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    postAdminAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAdminRequest"];
            };
        };
        responses: {
            /** @description Administrator created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    deleteAdminAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Administrator deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    patchAdminAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusRequest"];
            };
        };
        responses: {
            /** @description Updated administrator */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    postAdminAdminResetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Temporary password result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetPasswordResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getDashboard: {
        parameters: {
            query: {
                date: components["parameters"]["BusinessDate"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard aggregates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    listWorklogs: {
        parameters: {
            query?: {
                from?: components["parameters"]["DateFrom"];
                to?: components["parameters"]["DateTo"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daily worklogs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorklogListResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    createWorklog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorklogRequest"];
            };
        };
        responses: {
            /** @description Worklog saved */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorklogResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getWorklog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                work_date: components["parameters"]["WorkDate"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daily worklog */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorklogResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    updateWorklog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                work_date: components["parameters"]["WorkDate"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorklogRequest"];
            };
        };
        responses: {
            /** @description Worklog saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorklogResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    deleteWorklog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                work_date: components["parameters"]["WorkDate"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Worklog deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    listTurnovers: {
        parameters: {
            query?: {
                from?: components["parameters"]["DateFrom"];
                to?: components["parameters"]["DateTo"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daily turnovers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnoverListResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    createTurnover: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnoverRequest"];
            };
        };
        responses: {
            /** @description Turnover saved */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnoverResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getTurnover: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                turnover_date: components["parameters"]["TurnoverDate"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daily turnover */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnoverResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    updateTurnover: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                turnover_date: components["parameters"]["TurnoverDate"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnoverRequest"];
            };
        };
        responses: {
            /** @description Turnover saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnoverResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    deleteTurnover: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                turnover_date: components["parameters"]["TurnoverDate"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Turnover deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    listDreams: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dreams */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DreamListResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    createDream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DreamRequest"];
            };
        };
        responses: {
            /** @description Dream created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DreamResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getDream: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dream_id: components["parameters"]["DreamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DreamResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    updateDream: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dream_id: components["parameters"]["DreamId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DreamRequest"];
            };
        };
        responses: {
            /** @description Dream updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DreamResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    deleteDream: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dream_id: components["parameters"]["DreamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dream deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    listGoals: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Goals */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalListResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    createGoal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalRequest"];
            };
        };
        responses: {
            /** @description Goal created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getGoal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: components["parameters"]["GoalId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Goal */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    updateGoal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: components["parameters"]["GoalId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalRequest"];
            };
        };
        responses: {
            /** @description Goal updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    deleteGoal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: components["parameters"]["GoalId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Goal deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    listCalendarEvents: {
        parameters: {
            query: {
                from: components["parameters"]["CalendarFrom"];
                to: components["parameters"]["CalendarTo"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Calendar occurrences */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarEventListResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    createCalendarEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalendarEventRequest"];
            };
        };
        responses: {
            /** @description Calendar event created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarEventResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getCalendarEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: components["parameters"]["CalendarEventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Calendar event */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarEventResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    updateCalendarEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: components["parameters"]["CalendarEventId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalendarEventRequest"];
            };
        };
        responses: {
            /** @description Calendar event updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarEventResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    deleteCalendarEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: components["parameters"]["CalendarEventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Calendar event deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    listReviews: {
        parameters: {
            query?: {
                from?: components["parameters"]["DateFrom"];
                to?: components["parameters"]["DateTo"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reviews */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewListResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_type: components["parameters"]["ReviewType"];
                period_start: components["parameters"]["ReviewPeriodStart"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Review */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    updateReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_type: components["parameters"]["ReviewType"];
                period_start: components["parameters"]["ReviewPeriodStart"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description Review saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getWorklogAnalytics: {
        parameters: {
            query: {
                from?: components["parameters"]["DateFrom"];
                to?: components["parameters"]["DateTo"];
                granularity: components["parameters"]["AnalyticsGranularity"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Worklog analytics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getTurnoverAnalytics: {
        parameters: {
            query: {
                from?: components["parameters"]["DateFrom"];
                to?: components["parameters"]["DateTo"];
                granularity: components["parameters"]["AnalyticsGranularity"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Turnover analytics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getGoalAnalytics: {
        parameters: {
            query: {
                from?: components["parameters"]["DateFrom"];
                to?: components["parameters"]["DateTo"];
                granularity: components["parameters"]["AnalyticsGranularity"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Goal analytics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsResponse"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
}
