import { Activity, ArrowUpRight, ShieldCheck } from "lucide-react";
import type { ReactNode } from "react";
import { Link } from "react-router-dom";
import { HealthIndicator } from "@/components/layout/navigation";

export function AuthLayout({ health, children }: { health: { isPending: boolean; isSuccess: boolean }; children: ReactNode }) {
  return <div className="auth-page min-h-[100dvh] bg-canvas text-ink">
    <header className="border-b border-outline/75 bg-surface/95 shadow-hairline"><div className="mx-auto flex min-h-[72px] max-w-6xl items-center justify-between gap-4 px-5 sm:px-8"><Link to="/" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-control bg-brand-700 text-sm font-black text-white shadow-brand-glow">JL</span><span><span className="block text-[11px] font-bold uppercase tracking-[0.16em] text-brand-700">JL Growth</span><span className="block text-sm font-bold text-ink">JL团队生意成长管理系统</span></span></Link><HealthIndicator health={health} /></div></header>
    <main className="mx-auto grid min-h-[calc(100dvh-72px)] max-w-6xl items-center gap-10 px-5 py-8 sm:px-8 lg:grid-cols-[1fr_420px] lg:gap-20 lg:py-16"><section className="auth-story relative order-2 max-w-xl overflow-hidden rounded-hero border border-brand-100/75 bg-gradient-to-br from-brand-50/90 via-sky-50/65 to-amber-50/55 p-6 shadow-panel lg:order-none lg:p-8"><span className="pointer-events-none absolute -right-8 -top-8 h-36 w-36 rounded-full bg-amber-200/35 blur-2xl" aria-hidden="true" /><div className="relative"><div className="flex items-center gap-2 text-sm font-bold text-brand-800"><Activity size={17} />把今天经营清楚</div><h1 className="mt-5 text-4xl font-black leading-tight tracking-[-0.03em] text-ink sm:text-5xl">JL团队生意成长管理系统</h1><p className="mt-6 text-xl font-semibold leading-8 text-ink">让目标、行动与结果，在一个工作台里对齐。</p><p className="mt-3 text-base leading-7 text-ink-muted">记录个人成长和经营过程，逐步建立属于你的长期工作节奏。</p><div className="mt-8 flex items-center gap-3 text-sm text-ink-faint"><ShieldCheck size={17} className="text-brand-700" /><span>账号数据按用户严格隔离</span><ArrowUpRight size={15} aria-hidden="true" /></div></div></section><div className="order-1 lg:order-none">{children}</div></main>
  </div>;
}
