import { useQuery } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { getAnalytics, getFinanceAnalytics, getTeamAnalytics, type AnalyticsResponse, type AuthResponse } from "@/api/client";
import { PageHeader } from "@/components/ui/page-header";
import { Panel } from "@/components/ui/panel";
import { DataTable, TableBody, TableCell, TableHead, TableRow } from "@/components/ui/table";
import { EmptyState, ErrorState, LoadingState } from "@/components/ui/state-block";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { formatMoney } from "@/lib/money";

type Metric = "worklogs" | "turnover" | "goals" | "team" | "finance";
type Range = "week" | "month" | "year" | "custom";
const metricLabels: Record<Metric, string> = { worklogs: "工作量", turnover: "营业额", goals: "目标", team: "团队", finance: "财务" };

function isoDate(value: Date) { return value.toISOString().slice(0, 10); }
function datesFor(range: Range) { const now = new Date(); const to = new Date(now); to.setDate(to.getDate() + 1); const from = new Date(now); if (range === "week") from.setDate(from.getDate() - 6); if (range === "month") from.setDate(1); if (range === "year") { from.setMonth(0); from.setDate(1); } return { from: isoDate(from), to: isoDate(to), granularity: range === "year" ? "month" as const : "day" as const }; }

export function AnalyticsPage({ authResponse }: { authResponse: AuthResponse }) {
  const accountId = authResponse.data.account.id;
  const [metric, setMetric] = useState<Metric>("worklogs");
  const [range, setRange] = useState<Range>("week");
  const defaults = datesFor(range);
  const [customFrom, setCustomFrom] = useState(datesFor("month").from);
  const [customTo, setCustomTo] = useState(datesFor("month").to);
  const from = range === "custom" ? customFrom : defaults.from;
  const to = range === "custom" ? customTo : defaults.to;
  const granularity = range === "year" ? "month" : "day";
  const query = useQuery({ queryKey: ["user", accountId, "analytics", metric, from, to, granularity], queryFn: () => metric === "finance" ? getFinanceAnalytics(from, to, granularity) : metric === "team" ? getTeamAnalytics(from, to, granularity) : getAnalytics(metric, from, to, granularity) });
  return <div className="space-y-6">
    <PageHeader eyebrow="真实记录" title="数据统计" description="按领域和时间范围查看当前账号已经保存的真实聚合结果。" />
    <Tabs value={metric} onValueChange={(value) => setMetric(value as Metric)}><TabsList aria-label="统计领域"><TabsTrigger value="worklogs">工作量</TabsTrigger><TabsTrigger value="turnover">营业额</TabsTrigger><TabsTrigger value="goals">目标</TabsTrigger><TabsTrigger value="team">团队</TabsTrigger><TabsTrigger value="finance">财务</TabsTrigger></TabsList></Tabs>
    <div className="flex flex-col gap-3 rounded-lg border border-slate-200 bg-white p-3 sm:flex-row sm:items-center sm:justify-between"><div className="inline-flex flex-wrap gap-1" role="group" aria-label="统计时间范围">{([['week', '本周'], ['month', '本月'], ['year', '本年'], ['custom', '自定义']] as const).map(([value, label]) => <button key={value} type="button" aria-pressed={range === value} onClick={() => setRange(value)} className={`min-h-9 rounded-md px-3 text-sm font-semibold ${range === value ? "bg-teal-700 text-white" : "text-slate-600 hover:bg-slate-100"}`}>{label}</button>)}</div>{range === "custom" && <div className="flex flex-col gap-2 sm:flex-row"><DateField label="开始日期" value={customFrom} onChange={setCustomFrom} /><DateField label="结束日期" value={customTo} onChange={setCustomTo} /></div>}<p className="text-xs text-slate-500">{from} 至 {to}</p></div>
    {query.isPending ? <LoadingState label="正在计算统计" /> : query.isError ? <ErrorState message="统计暂时无法加载" onRetry={() => void query.refetch()} /> : query.data.data.buckets.length ? <AnalyticsWorkspace metric={metric} data={query.data} /> : <EmptyState title={`${metricLabels[metric]}暂无统计记录`} description="在当前时间范围保存业务记录后，这里会显示真实聚合结果。" />}
  </div>;
}

function AnalyticsWorkspace({ metric, data }: { metric: Metric; data: AnalyticsResponse }) {
  const buckets = data.data.buckets;
  const totals = useMemo(() => buckets.reduce((sum, bucket) => ({ actions: sum.actions + bucket.action_count, reading: sum.reading + bucket.reading_minutes, audio: sum.audio + bucket.audio_minutes, pv: sum.pv + Number(bucket.pv), net: sum.net + Number(bucket.net_amount), goals: sum.goals + bucket.goal_count, completed: sum.completed + bucket.completed_count, income: sum.income + Number(bucket.income_amount ?? 0), expense: sum.expense + Number(bucket.expense_amount ?? 0) }), { actions: 0, reading: 0, audio: 0, pv: 0, net: 0, goals: 0, completed: 0, income: 0, expense: 0 }), [buckets]);
  const last = buckets[buckets.length - 1];
  const kpis = metric === "worklogs" ? [["行动总数", String(totals.actions)], ["读书分钟", String(totals.reading)], ["音频分钟", String(totals.audio)]] : metric === "turnover" ? [["累计 PV", String(totals.pv)], ["净营业额", formatMoney(totals.net.toFixed(2))], ["记录周期", `${buckets.length}`]] : metric === "goals" ? [["目标数", String(totals.goals)], ["已完成", String(totals.completed)], ["完成率", totals.goals ? `${Math.round((totals.completed / totals.goals) * 100)}%` : "0%"]] : metric === "team" ? [["成员数", String(last.member_count ?? 0)], ["活跃成员", String(last.active_member_count ?? 0)], ["统计周期", `${buckets.length}`]] : [["收入", formatMoney(totals.income.toFixed(2))], ["支出", formatMoney(totals.expense.toFixed(2))], ["净现金流", formatMoney((totals.income - totals.expense).toFixed(2))]];
  return <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-3">{kpis.map(([label, value]) => <div key={label} className="rounded-lg border border-slate-200 bg-white p-5 shadow-panel"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold text-slate-950">{value}</p></div>)}</div><div className="grid gap-5 xl:grid-cols-[1.35fr_0.65fr]"><Panel title={`${metricLabels[metric]}趋势`} description="每个柱对应后端返回的一个聚合周期。"><Chart buckets={buckets} metric={metric} /></Panel><Panel title="结构摘要" description="仅对当前领域的返回字段做汇总。"><Structure metric={metric} totals={totals} last={last} /></Panel></div><Panel title="统计明细" description="保留各聚合周期的原始可读明细。"><Details metric={metric} buckets={buckets} /></Panel></div>;
}

function Chart({ buckets, metric }: { buckets: AnalyticsResponse["data"]["buckets"]; metric: Metric }) { const values = buckets.map((bucket) => metric === "finance" ? Math.max(Math.abs(Number(bucket.net_cash_flow ?? 0)), Number(bucket.income_amount ?? 0), Number(bucket.expense_amount ?? 0)) : metric === "team" ? bucket.member_count ?? 0 : metric === "turnover" ? Number(bucket.net_amount) : metric === "goals" ? bucket.goal_count : bucket.action_count); const max = Math.max(...values, 1); return <div className="grid min-h-56 grid-cols-[repeat(auto-fit,minmax(42px,1fr))] items-end gap-2 border-b border-slate-200 pb-2" aria-label={`${metricLabels[metric]}趋势图`}>{buckets.map((bucket, index) => <div key={bucket.period} className="flex min-w-0 flex-col items-center gap-2"><div className="w-full max-w-12 rounded-t bg-teal-600" style={{ height: `${Math.max(4, (values[index] / max) * 170)}px` }} title={`${bucket.period}: ${values[index]}`} /><span className="w-full truncate text-center text-[10px] text-slate-500">{bucket.period}</span></div>)}</div>; }
function Structure({ metric, totals, last }: { metric: Metric; totals: { actions: number; reading: number; audio: number; pv: number; net: number; goals: number; completed: number; income: number; expense: number }; last: AnalyticsResponse["data"]["buckets"][number] }) { const rows = metric === "worklogs" ? [["行动", totals.actions], ["阅读", totals.reading], ["音频", totals.audio]] : metric === "turnover" ? [["PV", totals.pv], ["净营业额", formatMoney(totals.net.toFixed(2))]] : metric === "goals" ? [["目标", totals.goals], ["完成", totals.completed]] : metric === "team" ? [["成员", last.member_count ?? 0], ["活跃", last.active_member_count ?? 0]] : [["收入", formatMoney(totals.income.toFixed(2))], ["支出", formatMoney(totals.expense.toFixed(2))]]; return <div className="space-y-3">{rows.map(([label, value]) => <div key={label} className="flex items-center justify-between border-b border-slate-100 pb-3 text-sm last:border-0"><span className="text-slate-600">{label}</span><strong>{value}</strong></div>)}</div>; }
function Details({ metric, buckets }: { metric: Metric; buckets: AnalyticsResponse["data"]["buckets"] }) { return <DataTable><TableHead><TableRow><TableCell asHeader>周期</TableCell><TableCell asHeader>{metric === "finance" ? "收入" : metric === "team" ? "成员" : "行动总数"}</TableCell><TableCell asHeader>{metric === "finance" ? "支出" : metric === "team" ? "活跃成员" : "读书 / 音频"}</TableCell><TableCell asHeader>{metric === "finance" ? "净现金流" : "PV / 净营业额"}</TableCell><TableCell asHeader>{metric === "team" ? "说明" : "目标"}</TableCell></TableRow></TableHead><TableBody>{buckets.map((bucket) => <TableRow key={bucket.period}><TableCell className="font-semibold">{bucket.period}</TableCell><TableCell>{metric === "finance" ? formatMoney(bucket.income_amount) : metric === "team" ? bucket.member_count ?? 0 : bucket.action_count}</TableCell><TableCell>{metric === "finance" ? formatMoney(bucket.expense_amount) : metric === "team" ? bucket.active_member_count ?? 0 : `${bucket.reading_minutes} / ${bucket.audio_minutes}`}</TableCell><TableCell>{metric === "finance" ? formatMoney(bucket.net_cash_flow) : `${bucket.pv} / ${formatMoney(bucket.net_amount)}`}</TableCell><TableCell>{metric === "team" ? "按加入日期聚合" : `${bucket.goal_count}（完成 ${bucket.completed_count}）`}</TableCell></TableRow>)}</TableBody></DataTable>; }
function DateField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="flex items-center gap-2 text-xs font-semibold text-slate-600"><span>{label}</span><input aria-label={label} type="date" value={value} onChange={(event) => onChange(event.target.value)} className="min-h-9 rounded-md border border-slate-300 bg-white px-2 text-sm" /></label>; }
